// Generated by CoffeeScript 1.12.7
var ANIMATION_END_NAME, ANIMATION_END_NAMES, IsPC, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, answerlists, apiURL, ask, css3Prefix, i, initLab, j, lab, len, load, loadWechatConfig, mTestElement, sendPost, shareContent, shareDescription, shareTitles, token;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Vue.component("slider", {
  template: '<div><div class="slider-list" v-bind:style="{transform: \'translate3d(\'+x+\'px,0,0)\',transitionDuration: duration+\'s\'}" ><slot/></div></div>',
  data: function() {
    return {
      root: null,
      moving: false,
      timeout: null,
      now: 0,
      max: 2,
      time: 3000,
      delay: 3000,
      duration: 0,
      offset: {
        resistance: 1,
        lastSlide: 1,
        scrollableArea: 320,
        isScrolling: false,
        lastw: 0,
        w: 320,
        x: 0,
        y: 0,
        deltaX: 0,
        deltaY: 0
      },
      slideNumber: 0,
      move: false,
      startTime: 0,
      x: 0,
      y: 0
    };
  },
  props: ['overpage'],
  watch: {
    overpage: function(newV, oldV) {
      if (newV) {
        return this.start();
      }
    }
  },
  methods: {
    start: function() {
      this.stopAll();
      return this.timeout = setTimeout((function(_this) {
        return function() {
          return _this.moveNext();
        };
      })(this), this.time);
    },
    moveNext: function() {
      this.stopAll();
      if (this.now >= this.max) {
        this.animationEnd();
        return false;
        this.now = 0;
        this.timeout = setTimeout((function(_this) {
          return function() {
            return _this.moveNext();
          };
        })(this), 10);
        return false;
      } else {
        this.offset.w = this.$el.offsetWidth;
        this.duration = 0.5;
        this.now = this.now + 1;
        this.x = -(this.now * this.offset.w);
        this.setSlideNumber(0);
      }
      return this.timeout = setTimeout((function(_this) {
        return function() {
          return _this.moveNext();
        };
      })(this), this.time);
    },
    stopAll: function() {
      return clearTimeout(this.timeout);
    },
    setSlideNumber: function(offset) {
      var round, slideNumber;
      round = offset ? (this.offset.deltaX < 0 ? 'ceil' : 'floor') : 'round';
      slideNumber = Math[round](this.x / (this.offset.scrollableArea / this.list.length));
      slideNumber += offset;
      slideNumber = Math.min(slideNumber, 0);
      return this.slideNumber = Math.max(-(this.list.length - 1), slideNumber) % this.list.length;
    },
    touchstart: function(evt) {
      var touch;
      touch = evt.touches[0];
      this.duration = 0;
      this.moved = false;
      this.startTime = +(new Date);
      this.offset.w = this.$el.offsetWidth;
      this.offset.x = touch.pageX;
      this.offset.y = touch.pageY;
      this.offset.lastw = this.x;
      this.offset.lastSlide = -(this.list.length - 1);
      this.offset.scrollableArea = this.offset.w * this.list.length;
      return this.setSlideNumber(0);
    },
    touchmove: function(evt) {
      var pageX, touch;
      touch = evt.touches[0];
      this.offset.deltaX = touch.pageX - this.offset.x;
      pageX = touch.pageX;
      this.x = this.offset.deltaX / this.offset.resistance + this.offset.lastw;
      this.offset.resistance = this.slideNumber === 0 && this.offset.deltaX > 0 ? pageX / this.offset.w + 1.25 : this.slideNumber === this.offset.lastSlide && this.offset.deltaX < 0 ? (this.offset.w - Math.abs(pageX)) / this.offset.w + 1.25 : 1;
      return this.moved = true;
    },
    touchend: function(evt) {
      var oldslideNumber;
      if (this.moved) {
        oldslideNumber = this.slideNumber;
        this.setSlideNumber(+(new Date) - this.startTime < 1000 && Math.abs(this.offset.deltaX) > 15 ? (this.offset.deltaX < 0 ? -1 : 1) : 0);
        this.x = this.slideNumber * this.offset.w;
        this.duration = 0.2;
        if (this.slideNumber === 0 && oldslideNumber === -(this.list.length - 1)) {
          this.x = (oldslideNumber - 1) * this.offset.w;
        }
        if (oldslideNumber === 0 && this.slideNumber === -(this.list.length - 1)) {
          return this.x = 1 * this.offset.w;
        }
      }
    },
    animationEnd: function() {
      this.$el.addEventListener('touchstart', this.touchstart.bind(this));
      this.$el.addEventListener('touchmove', this.touchmove.bind(this));
      return this.$el.addEventListener('touchend', this.touchend.bind(this));
    }
  },
  mounted: function(el) {
    return this.list = this.$el.children[0].children;
  }
});

apiURL = "api.giccoo.com";

load = {};

lab = {};

token = null;

shareContent = {
  title: "雅诗兰黛美肌万能研究室",
  desc: "品牌合作Html5页面，用户可点击进入进行答题，生成属于自己的肌肤报告。",
  link: "http://m.giccoo.com/esteelauder/",
  imgUrl: "http://m.giccoo.com/esteelauder/img/share.jpg",
  success: function() {},
  cancel: function() {}
};

answerlists = [
  [
    {
      selected: false,
      text: "小细纹干嘛大惊小怪？可能最近笑太多！",
      id: 3
    }, {
      selected: false,
      text: "照镜子感觉老了许多，先补水再说！",
      id: 2
    }, {
      selected: false,
      text: "没事按摩一下，皱纹慢慢会消失！",
      id: 1
    }
  ], [
    {
      selected: false,
      text: "面色不均匀，压点粉饼就好了~",
      id: 3
    }, {
      selected: false,
      text: "面色发黄？涂点腮红拯救一下！",
      id: 2
    }, {
      selected: false,
      text: "脸色有点暗沉，多睡两觉补一补~",
      id: 1
    }
  ], [
    {
      selected: false,
      text: "小脸不Q弹，补点胶原蛋白~~",
      id: 3
    }, {
      selected: false,
      text: "脸不紧致，赶紧用按摩仪提拉一下！",
      id: 2
    }, {
      selected: false,
      text: "粗糙起皮，做个去角质就好啦~~",
      id: 1
    }
  ]
];

answerlists[0].sort(function() {
  if (Math.random() > 0.5) {
    return -1;
  } else {
    return 1;
  }
});

answerlists[1].sort(function() {
  if (Math.random() > 0.5) {
    return -1;
  } else {
    return 1;
  }
});

answerlists[2].sort(function() {
  if (Math.random() > 0.5) {
    return -1;
  } else {
    return 1;
  }
});

shareTitles = ["鲜嫩丝滑奶茶肌", "光泽亮润陶瓷肌", "吹弹可破蛋白肌"];

shareDescription = ["但是你的皱纹一带一条指数偏高", "但是你的脸色亮度有待提升", "但是你的小脸紧致程度有所下降"];

window.onload = function() {
  var MK, body;
  if (IsPC() && mobile) {
    return window.location.href = "pc.html";
  }
  body = document.getElementsByTagName("body")[0];
  MK = body.offsetWidth / body.offsetHeight;
  if (body.offsetHeight <= 480 || MK > 0.65) {
    body.className = "iphone4";
  }
  if (body.offsetWidth >= 640) {
    body.className = "pc";
  }
  return load = new Vue({
    el: '#load',
    data: {
      loadend: false,
      show: true,
      number: 0,
      animatedNumber: 0
    },
    watch: {
      number: function(newValue, oldValue) {
        var animate, vm;
        vm = this;
        animate = function() {
          if (TWEEN.update()) {
            requestAnimationFrame(animate);
          }
        };
        new TWEEN.Tween({
          tweeningNumber: oldValue
        }).easing(TWEEN.Easing.Quadratic.Out).to({
          tweeningNumber: newValue
        }, 700).onUpdate(function() {
          vm.animatedNumber = this.tweeningNumber.toFixed(0);
        }).start();
        animate();
      },
      animatedNumber: function(newValue, oldValue) {
        if (parseInt(newValue) === 100) {
          return setTimeout((function(_this) {
            return function() {
              _this.loadend = true;
              return lab.started = true;
            };
          })(this), 100);
        }
      }
    },
    mounted: function() {
      this.number = 15;
      console.log(this, this.$el);
      return ask();
    }
  });
};

initLab = function() {
  return lab = new Vue({
    el: "#lab",
    data: {
      started: false,
      startquestion: false,
      startprinter: false,
      answerFinished: false,
      answer: 0,
      score: [0, 0, 0],
      nickname: "",
      waiting: false,
      printerover: false,
      overpage: false,
      sended: false,
      sharesuccess: false,
      shownote: false,
      touchdata: "up",
      printer: {
        title: "鲜嫩丝滑奶茶肌",
        description: "但是你的脸色亮度有待提升"
      },
      answerlist: answerlists,
      answerShow: [true, true, true]
    },
    methods: {
      startGo: function() {
        this.started = false;
        this.startquestion = true;
        return stm_clicki('send', 'event', '即刻开启', '点击', '开始页面');
      },
      selecteFun: function(answer, indexP, index) {
        console.log(indexP, this.answer);
        if (this.waiting || this.answerFinished || this.answer === 3) {
          return false;
        }
        if (indexP !== this.answer) {
          return false;
        }
        answer.selected = true;
        if (this.answer < 2) {
          this.answerShow[this.answer] = false;
        }
        if (this.answer <= 2) {
          this.score[this.answer] = answer.id;
        }
        this.answer = this.answer + 1;
        if (this.answer === 3) {
          this.answerFinished = true;
        }
        return stm_clicki('send', 'event', '以下哪种情况最符合你？', '第' + indexP + '题', '答案' + answer.id);
      },
      startPrinterFun: function() {
        var p;
        this.started = false;
        this.startquestion = false;
        this.startprinter = true;
        this.printerover = true;
        p = document.getElementById("printer-page");
        if (this.score[0] >= this.score[1] && this.score[0] >= this.score[2]) {
          this.printer.title = shareTitles[0];
        } else if (this.score[1] >= this.score[2] && this.score[1] >= this.score[0]) {
          this.printer.title = shareTitles[1];
        } else if (this.score[2] >= this.score[1] && this.score[2] >= this.score[0]) {
          this.printer.title = shareTitles[2];
        } else {
          this.printer.title = shareTitles[0];
        }
        if (this.score[2] <= this.score[1] && this.score[2] <= this.score[0]) {
          this.printer.description = shareDescription[2];
        } else if (this.score[1] <= this.score[2] && this.score[1] <= this.score[0]) {
          this.printer.description = shareDescription[1];
        } else if (this.score[0] <= this.score[1] && this.score[0] <= this.score[2]) {
          this.printer.description = shareDescription[0];
        } else {
          this.printer.description = shareDescription[2];
        }
        return stm_clicki('send', 'event', '提交查看你的肌密报告', '点击', '答题页面');
      },
      sendPostFun: function() {
        var self;
        if (this.sended) {
          return false;
        }
        self = this;
        axios.get("http://" + apiURL + "/esteelauder/shareTo/?id=" + this.score.join("-")).then(function(msg) {
          if (msg.data.recode === 200) {
            self.sended = true;
            self.sharesuccess = true;
          }
          if (msg.data.recode !== 200) {
            return console.log(msg);
          }
        });
        return stm_clicki('send', 'event', '发布你的肌密报告', '点击', '产品列表页');
      },
      closeshare: function() {
        this.sharesuccess = false;
        return this.sended = false;
      },
      closenote: function() {
        return this.shownote = false;
      },
      openNoteFun: function() {
        this.shownote = true;
        return stm_clicki('send', 'event', '*详细活动规则请点击查看', '点击', '产品列表页');
      },
      gotoProFun: function(de) {
        if (!this.printerover) {
          return false;
        }
        this.printerover = false;
        this.overpage = true;
        stm_clicki('send', 'event', '下一页', '滑动', '报告页面');
        if (this.nickname !== "") {
          return stm_clicki('send', 'event', '填写昵称', '输入', this.nickname);
        }
      }
    },
    directives: {
      touch: {
        "default": {
          x: 0,
          y: 0,
          start: false,
          moving: false
        },
        inserted: function(el) {},
        bind: function(el, binding, vnode) {
          el.addEventListener("touchstart", binding.def.touchstart.bind(binding));
          el.addEventListener("touchmove", binding.def.touchmove.bind(binding));
          el.addEventListener("touchend", binding.def.touchend.bind(binding));
          el.addEventListener("mousedown", binding.def.touchstart.bind(binding));
          el.addEventListener("mousemove", binding.def.touchmove.bind(binding));
          return el.addEventListener("mouseup", binding.def.touchend.bind(binding));
        },
        touchstart: function(evt) {
          var touch;
          evt.preventDefault();
          if (evt.type === "mousedown") {
            this.def["default"].x = evt.pageX;
            this.def["default"].y = evt.pageY;
            return this.def["default"].start = true;
          } else {
            touch = evt.touches[0];
            this.def["default"].x = touch.pageX;
            this.def["default"].y = touch.pageY;
            return this.def["default"].start = true;
          }
        },
        touchmove: function(evt) {
          var deY, touch;
          evt.preventDefault();
          if (!this.def["default"].start) {
            return false;
          }
          if (evt.type === "mousemove") {
            touch = evt;
          } else {
            touch = evt.touches[0];
          }
          this.def["default"].moving = true;
          deY = this.def["default"].y - touch.pageY;
          if (deY > 50) {
            this.def["default"].start = false;
            this.value("up");
            return false;
          }
          if (deY < -50) {
            this.def["default"].start = false;
            this.value("down");
            return false;
          }
        },
        touchend: function(evt) {
          evt.preventDefault();
          this.def["default"].start = false;
          return this.def["default"].moving = false;
        }
      }
    }
  });
};

ask = function() {
  axios.defaults.withCredentials = true;
  return axios.get("http://" + apiURL + "/esteelauder/ask").then(function(msg) {
    console.log("msg:", msg.data);
    if (msg.data.recode === 200) {
      load.number = 100;
      token = msg.data.token;
    } else {
      window.location.href = "https://api.weibo.com/oauth2/authorize?client_id=1605288503&response_type=code&redirect_uri=http://" + apiURL + "/esteelauder/";
    }
    return initLab();
  })["catch"](function(err) {
    return initLab();
  });
};

sendPost = function(callback) {
  return axios.get("http://" + apiURL + "/esteelauder/shareTo").then(function(msg) {
    if (msg.data.recode === 200) {
      callback();
    }
    if (msg.data.recode !== 200) {
      return console.log(msg);
    }
  });
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/api/config?url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};

IsPC = function() {
  var Agents, flag, userAgentInfo, v;
  userAgentInfo = navigator.userAgent;
  Agents = new Array('Android', 'iPhone', 'SymbianOS', 'Windows Phone', 'iPad', 'iPod');
  flag = true;
  v = 0;
  while (v < Agents.length) {
    if (userAgentInfo.indexOf(Agents[v]) > 0) {
      flag = false;
      break;
    }
    v++;
  }
  return flag;
};
