// Generated by CoffeeScript 1.9.1
window.onload = function() {
  $(".homepage")[0].addEventListener("touchstart", function(evt) {
    return evt.preventDefault();
  });
  $(".homepage")[0].addEventListener("touchmove", function(evt) {
    return evt.preventDefault();
  });
  return $(".homepage")[0].addEventListener("touchend", function(evt) {
    return $(".homepage").addClass("next");
  });
};
