"use strict";function _defineProperty(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var ANIMATION_END_NAME,ANIMATION_END_NAMES,IsPC,NumberToChinese,SectionToChinese,TRANSITION_END_NAME,TRANSITION_END_NAMES,TrueH,TrueW,VENDORS,_cache,_public,_runTime,_second,_startCache,_testTime,apiLink,apiUrl,chnNumChar,chnUnitChar,chnUnitSection,css3Prefix,i,imageurl,init,isAndroid,j,len1,loadWechatConfig,loading,mTestElement,main,musicIconCache,musicLineCache,neteaseShareImage,sended,sys,tryThis,ugc,ugcCache;for(VENDORS=["Moz","webkit","ms","O"],TRANSITION_END_NAMES={Moz:"transitionend",webkit:"webkitTransitionEnd",ms:"MSTransitionEnd",O:"oTransitionEnd"},ANIMATION_END_NAMES={Moz:"animationend",webkit:"webkitAnimationEnd",ms:"MSAnimationEnd",O:"oAnimationEnd"},mTestElement=document.createElement("div"),j=0,len1=VENDORS.length;j<len1&&!((css3Prefix=i=VENDORS[j])+"Transition"in mTestElement.style);j++)css3Prefix=!1;css3Prefix&&(TRANSITION_END_NAME=TRANSITION_END_NAMES[css3Prefix],ANIMATION_END_NAME=ANIMATION_END_NAMES[css3Prefix]),loadWechatConfig=function e(){var t,n,i;i=encodeURIComponent(window.location.href.split("#")[0]),(t=document.createElement("script")).src="//api.giccoo.com/api/config?url="+i,(n=document.getElementsByTagName("script")[0]).parentNode.insertBefore(t,n)},IsPC=function e(){var t,n,i,o;for(i=navigator.userAgent,t=new Array("Android","iPhone","SymbianOS","Windows Phone","iPad","iPod"),n=!0,o=0;o<t.length;){if(0<i.indexOf(t[o])){n=!1;break}o++}return n},isAndroid=-1<navigator.userAgent.indexOf("Android")||-1<navigator.userAgent.indexOf("Adr"),//android终端
Vue.directive("resetInput",{inserted:function e(t){isAndroid||t.addEventListener("blur",function(){var e;(e=document.getElementById("reset-input"))||((e=document.createElement("INPUT")).type="text",e.style.height="0px",e.style.width="0px",e.style.position="absolute",e.id="reset-input",document.body.prepend(e)),e.focus(),e.blur()})}}),// @codekit-prepend "../../libs/vue/vue-resetinput"
Vue.component("form-grounp",{template:'<div class="form"> <div v-for="item,index in form" class="form-group" :class="\'type-\'+type[item.type]+(item.class?\' \'+item.class:\'\')"> <label :for="item.id" v-if="item.label">{{item.label}}</label> <input v-reset-input :id="item.id" :placeholder="item.placeholder" v-if="type[item.type] == \'input\'" v-model="item.value" type="text"> <input v-reset-input :id="item.id" :placeholder="item.placeholder" v-if="type[item.type] == \'number\'" v-model="item.value" type="number"> <div v-if="type[item.type] == \'select\'" class="select"> <span>{{getOptionsName(item)}}</span> <select :id="item.id" v-model="item.value" v-if="!item.array"> <option v-for="(item, key) in item.options" :disabled="!item" :value="key">{{key}}</option> </select> <select :id="item.id" v-model="item.value" v-if="item.array"> <option v-for="(item, index) in item.options" :disabled="item.disabled" :value="item.val">{{item.name}}</option> </select> </div> </div> <slot></slot> <div @click="submit" class="btn-submit"><img src="./img/btn-submit.png" /></div> </div>',data:function e(){return{submiting:!1,type:{input:"input",number:"number",select:"select",checkbox:"checkbox"}}},props:{form:{default:{}}},watch:{form:{handler:function e(t){return console.log("form:",t)},deep:!0}},methods:{getOptionsName:function e(t){var n,i,o,a;if(t.array){for(i=0,o=(a=t.options).length;i<o;i++)if((n=a[i]).val===t.value)return n.name;return t.options[0].name}return""===t.value?Object.keys(t.options)[0]:t.value},submit:function e(t){var n,i,o,a;for(i in n={},console.log("first Time.."),o=this.form)a=o[i],n[i]=a.value;// console.log "submit:",data
return this.$emit("submit",n)}},mounted:function e(t){var n,o,a,s,r;// console.log "el:",this,this.form
for(n in a=[],o=(s=this).form)"select"===(r=o[n]).type&&(console.log("form.".concat(n,".options")),this.$watch("form.".concat(n,".options"),function(e){return console.log("changed:",e)},{deep:!0})),null!=r.link&&"select"===r.type?a.push(this.$watch("form.".concat(n),function(e,t){var n,o,a;if(null==s.form[e.link])return!1;if(s.form[e.link].options=e.options[e.value],s.form[e.link].array)return console.log(e.link,s.form[e.link].value,e.options[e.value][0].val),s.form[e.link].value=e.options[e.value][0].val;for(a=[],i=n=0,o=Object.keys(e.options[e.value]).length;0<=o?n<o:o<n;i=0<=o?++n:--n){if(e.options[e.value][Object.keys(e.options[e.value])[i]]){s.form[e.link].value=Object.keys(e.options[e.value])[i];break}a.push(void 0)}return a},{deep:!0})):a.push(void 0);return a}}),Vue.component("player",{template:'<div class="player" :class="{play: playing, pause: !playing}" @click="change"> <div class="icon-play" :class="{play: playing, pause: !playing}"> <svg v-if="!icon" v-show="!playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-39"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 18.5,22 18.5,14 12,10 z M 18.5,22 25,18 25,18 18.5,14 z"></path></svg> <svg v-if="!icon" v-show="playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-40"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 16,26 16,10 12,10 z M 21,26 25,26 25,10 21,10 z"></path></svg> </div> <audio :src="src" :autoplay="autoplay" :preload="preload" :loop="loop"></audio> <img v-if="thumb" :src="thumb" /> <slot></slot> </div>',data:function e(){return{playing:!1,stoped:!1}},props:{fill:{default:"black"},name:{default:!1},src:{default:"./mp3/bgm.mp3"},thumb:{default:!1},autoplay:{default:!1},preload:{default:!1},loop:{default:!1},callback:{default:!1},icon:{default:!1}},methods:{play:function e(){var t;// @audio.load()
return t=this.$emit("play",this),this.playing=!0,this.audio.play()},pause:function e(){var t;return t=this.$emit("pause",this),this.audio.pause(),this.playing=!1},ended:function e(){return this.playing=!1},change:function e(){return this.playing?(this.audio.pause(),this.stoped=!0):(this.audio.play(),this.stoped=!1)}},
// computed:
mounted:function e(t){
// console.log @name
return this.audio=this.$el.children[1],// console.log @audio
// @audioOther = @$el.children[2]
this.audio.addEventListener("pause",this.pause.bind(this)),this.audio.addEventListener("play",this.play.bind(this)),this.audio.addEventListener("ended",this.ended.bind(this))}}),// @audio.play()
// console.log @audio,@audioOther,@playing
String.prototype.gblen=function(){var e,t,n;for(i=e=t=0,n=this.length;0<=n?e<n:n<e;i=0<=n?++e:--e)127<this.charCodeAt(i)||94===this.charCodeAt(i)?t+=2:t++;return t},loadWechatConfig=function e(){var t,n,i;i=encodeURIComponent(window.location.href.split("#")[0]),(t=document.createElement("script")).src="//api.giccoo.com/api/config?url="+i,(n=document.getElementsByTagName("script")[0]).parentNode.insertBefore(t,n)},IsPC=function e(){var t,n,i,o;for(i=navigator.userAgent,t=new Array("Android","iPhone","SymbianOS","Windows Phone","iPad","iPod"),n=!0,o=0;o<t.length;){if(0<i.indexOf(t[o])){n=!1;break}o++}return n},Vue.component("player",{template:'<div class="player" :class="{play: playing, pause: !playing}" @click="change"> <div class="icon-play" :class="{play: playing, pause: !playing}"> <svg v-if="!icon" v-show="!playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-39"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 18.5,22 18.5,14 12,10 z M 18.5,22 25,18 25,18 18.5,14 z"></path></svg> <svg v-if="!icon" v-show="playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-40"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 16,26 16,10 12,10 z M 21,26 25,26 25,10 21,10 z"></path></svg> </div> <audio :src="src" :autoplay="autoplay" :preload="preload" :loop="loop"></audio> <img v-if="thumb" :src="thumb" /> <slot></slot> </div>',data:function e(){return{playing:!1,stoped:!1}},props:{fill:{default:"black"},name:{default:!1},src:{default:"./mp3/bgm.mp3"},thumb:{default:!1},autoplay:{default:!1},preload:{default:!1},loop:{default:!1},callback:{default:!1},icon:{default:!1}},methods:{play:function e(){var t;// @audio.load()
return t=this.$emit("play",this),this.playing=!0,this.audio.play()},pause:function e(){var t;return t=this.$emit("pause",this),this.audio.pause(),this.playing=!1},ended:function e(){return this.playing=!1},change:function e(){return this.playing?(this.audio.pause(),this.stoped=!0):(this.audio.play(),this.stoped=!1)}},
// computed:
mounted:function e(t){
// console.log @name
return this.audio=this.$el.children[1],// console.log @audio
// @audioOther = @$el.children[2]
this.audio.addEventListener("pause",this.pause.bind(this)),this.audio.addEventListener("play",this.play.bind(this)),this.audio.addEventListener("ended",this.ended.bind(this))}}),// @audio.play()
// console.log @audio,@audioOther,@playing
loadWechatConfig=function e(){var t,n,i;i=encodeURIComponent(window.location.href.split("#")[0]),(t=document.createElement("script")).src="//api.giccoo.com/api/config?url="+i,(n=document.getElementsByTagName("script")[0]).parentNode.insertBefore(t,n)},IsPC=function e(){var t,n,i,o;for(i=navigator.userAgent,t=new Array("Android","iPhone","SymbianOS","Windows Phone","iPad","iPod"),n=!0,o=0;o<t.length;){if(0<i.indexOf(t[o])){n=!1;break}o++}return n},Vue.component("player",{template:'<div class="player" :class="{play: playing, pause: !playing}" @click="change"> <div class="icon-play" :class="{play: playing, pause: !playing}"> <svg v-if="!icon" v-show="!playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-39"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 18.5,22 18.5,14 12,10 z M 18.5,22 25,18 25,18 18.5,14 z"></path></svg> <svg v-if="!icon" v-show="playing" height="100%" version="1.1" viewBox="0 0 36 36" width="100%"><use class="ytp-svg-shadow" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#ytp-id-40"></use><path :fill="fill" class="ytp-svg-fill" d="M 12,26 16,26 16,10 12,10 z M 21,26 25,26 25,10 21,10 z"></path></svg> </div> <audio :src="src" :autoplay="autoplay" :preload="preload" :loop="loop"></audio> <img v-if="thumb" :src="thumb" /> <slot></slot> </div>',data:function e(){return{playing:!1,stoped:!1}},props:{fill:{default:"black"},name:{default:!1},src:{default:"./mp3/bgm.mp3"},thumb:{default:!1},autoplay:{default:!1},preload:{default:!1},loop:{default:!1},callback:{default:!1},icon:{default:!1}},methods:{play:function e(){var t;// @audio.load()
return t=this.$emit("play",this),this.playing=!0,this.audio.play()},pause:function e(){var t;return t=this.$emit("pause",this),this.audio.pause(),this.playing=!1},ended:function e(){return this.playing=!1},change:function e(){return this.playing?(this.audio.pause(),this.stoped=!0):(this.audio.play(),this.stoped=!1)}},
// computed:
mounted:function e(t){
// console.log @name
return this.audio=this.$el.children[1],// console.log @audio
// @audioOther = @$el.children[2]
this.audio.addEventListener("pause",this.pause.bind(this)),this.audio.addEventListener("play",this.play.bind(this)),this.audio.addEventListener("ended",this.ended.bind(this))}}),// @audio.play()
// console.log @audio,@audioOther,@playing
IsPC=function e(){var t,n,i,o;for(i=navigator.userAgent,t=new Array("Android","iPhone","SymbianOS","Windows Phone","iPad","iPod"),n=!0,o=0;o<t.length;){if(0<i.indexOf(t[o])){n=!1;break}o++}return n},loadWechatConfig=function e(){var t,n,i;i=encodeURIComponent(window.location.href.split("#")[0]),(t=document.createElement("script")).src="//api.giccoo.com/api/config?url="+i,(n=document.getElementsByTagName("script")[0]).parentNode.insertBefore(t,n)},// @codekit-prepend "coffee/css3Prefix"
// @codekit-prepend "../../libs/coffee/loadWechatConfig"
// @codekit-prepend "../../libs/coffee/IsPC"
// @codekit-prepend "../../libs/vue/vue-register"
// @codekit-prepend "../../libs/vue/vue-player"
// @codekit-prepend "../../libs/coffee/String"
axios.defaults.withCredentials=!0,TrueW=640,TrueH=1138,imageurl="//api.giccoo.com/api/upload/image64/",apiUrl="//api.giccoo.com/YearOfThePig",// apiLink = "//localhost:3000/"
apiLink="//g.giccoo.com/",// apiLink = "http://192.168.3.53:3000/"
// apiUrl = "http://localhost:8881/Levi"
main={},sys="",sended=[!(loading={}),!(_public={})],_runTime=_startCache=_cache=ugcCache=musicIconCache=musicLineCache=ugc=null,_testTime=_second=0,neteaseShareImage=function e(){var t,n,i;return i="画山成岳",t="https://image.giccoo.com/upload/".concat(main.folder,"/")+main.shareImageLink+"@!large",n="https://activity.music.163.com/YearOfThePig/",// console.log picUrl,"orpheus://sharepic?picUrl="+encodeURIComponent(picUrl)+"&shareUrl="+encodeURIComponent(redirectUrl)+"&wbDesc="+encodeURIComponent(title1)+"&qqDesc="+encodeURIComponent(title1)
// window.location.href = "orpheus://sharepic?picUrl="+encodeURIComponent(picUrl)+"&shareUrl="+encodeURIComponent(redirectUrl)+"&wbDesc="+encodeURIComponent(title1)+"&qqDesc="+encodeURIComponent(title1)
console.log("share href:",t),CloudMusic.sharePic({picUrl:t,text:i,link:n})},window.onload=function(){var e,t;return TrueH=document.documentElement.clientHeight,TrueW=document.documentElement.clientWidth,e=0,-1<window.navigator.userAgent.indexOf("NeteaseMusic")?(sys="NeteaseMusic",t={name:"YearOfThePig",title:"Title",subTitle:"Description",text:"",picUrl:"http://m.giccoo.com/YearOfThePig/img/ico.jpg",link:"http://m.giccoo.com/YearOfThePig/"},CloudMusic.setShareData(t)):(loadWechatConfig(),wx.ready(function(){var e;return e={title:"Title",desc:"Description",link:"http://m.giccoo.com/YearOfThePig/",imgUrl:"http://m.giccoo.com/YearOfThePig/img/ico.jpg",success:function e(){},
// alert "success"
cancel:function e(){}},// alert "cancel"
wx.onMenuShareTimeline(e),wx.onMenuShareAppMessage(e),wx.onMenuShareQQ(e),wx.onMenuShareWeibo(e)})),// _public = new Vue
// 	el: "#public"
// 	data:
// 		note: true
// 		playing: false
// 	mounted: ->
// 		document.addEventListener "WeixinJSBridgeReady", ->
// 			_public.$children[0].change()
loading=new Vue({el:"#loading",data:{progress:0,mounted:!1,progressOn:100,isrun:!1},computed:{progressText:function e(){return NumberToChinese(this.progress)}},methods:{runHand:function e(){var t=this,n,i,o,a,s,r,l;return!this.isrun&&(s=document.documentElement.clientHeight,this.isrun=!0,o=document.getElementsByClassName("hand-left")[0],a=document.getElementsByClassName("hand-right")[0],n=document.getElementsByClassName("lucky-bag")[0],r=document.getElementsByClassName("bag-shadow")[0],i=1.2,l=.6,TweenMax.to(a,i,{y:s/2-.1*s}),TweenMax.to(o,i,{y:s/2-.1*s}),TweenMax.to(a,i,{rotation:10}),TweenMax.to(o,i,{rotation:-10}),TweenMax.to(a,.6,{y:.1*-s,delay:1.44}),TweenMax.to(o,.6,{y:.1*-s,delay:1.44}),TweenMax.to(r,1.2/3,{scale:0,delay:1.44}),TweenMax.to(n,.6,{y:-s/2,delay:1.44,onComplete:function e(){return console.log("aa"),t.next()}}))},next:function e(){return document.getElementById("load").className+=" fadeOut animated",_public.note=!1,main.mounted=!0,main.runHand(),setTimeout(function(){return document.getElementById("load").style.display="none",main.pageIndex=1},520)}},mounted:function e(){var t=this,n;// @.next() # for test
return this.mounted=!0,TrueH=document.documentElement.clientHeight,TrueW=document.documentElement.clientWidth,n=setInterval(function(){if(t.progress+=3,t.progress>=t.progressOn&&(t.progress=t.progressOn),70<=t.progress&&t.runHand(),100<=t.progress)return t.progress=100,clearInterval(n)},50)}}),init()},init=function e(){var t,n,o;return 640<=TrueW&&(TrueW=640),1138<=TrueH&&(TrueH=1138),o=2*TrueH<1200,n=Math.ceil(TrueW/640*94/TrueH*100),TrueH=document.documentElement.clientHeight,TrueW=document.documentElement.clientWidth,console.log(TrueW,TrueH),main=new Vue({el:"#main",data:(t={w:TrueW,h:TrueH,biger:TrueW/TrueH<.55,smaller:o,afterH:o?1.15*TrueH-TrueW/750*1029:TrueH-TrueW/750*1029,wy:!1,mounted:!0,loading:!1,playing:!1,noteText:"",noteTime:null,noteShow:!1,noteType:!0,pageInfoShow:!1,pageIndex:0,step:1,singerIndex:1,bgmPlay:!1,startgame:!1,folder:"",BGColor:"#ffffff",XY:"pageY",ugc:null,ugcsave:null,ugcold:null,pushed:!1,shareImageLink:null,cache:null,audioId:null,v:null,recordStarting:!1,authorization:!1,norecord:!0,uploaded:!1,imageUpdate:!1,allowPopShow:!1,count:0,videoIndex:0,videoIndexOld:0,lr:!0,form:{sex:{id:"sex",type:"select",link:"city",array:!0,value:0,options:[{name:"请选择称谓(男士/女士)",val:0},{name:"男士",val:1},{name:"女士",val:2}]},firstname:{id:"firstname",type:"input",placeholder:"请填写姓",value:""},username:{id:"username",type:"input",placeholder:"请填写名",value:""},mobile:{id:"mobile",type:"number",placeholder:"请填写电话号码",value:""}},
// 	city: {id:"city", type: "select", label: "城市", link: "dealer",value: Object.keys(_citys["请选择省份"])[0], options: _citys["请选择省份"] }
mask:1,text:"",nickname:"",mobile:"",musicLink:"",logId:"",openBtnShow:!0,default:{x:0},videoPop:!1,canUpload:!0,handCover:!1,last_update:0,lastX:0,lastY:0,lastZ:0,speed:4e3,maxSpeed:0,swing:!1,registerShow:!1,lotteryShow:!1,lotteryEndShow:!1,lotteryInfo:{id:null,random:null},regSubmited:!1,giveUp:!1,gameEnd:!1,noreg:!1,ugcShow:!1,regH:100,ugcType:1},_defineProperty(t,"nickname",""),_defineProperty(t,"message",""),_defineProperty(t,"messageIndex",1),_defineProperty(t,"messageInput",!1),_defineProperty(t,"musicName",""),_defineProperty(t,"white",!1),_defineProperty(t,"gameEnd",!1),_defineProperty(t,"formShow",!0),_defineProperty(t,"formBoxShow",!1),_defineProperty(t,"carIndex",1),_defineProperty(t,"allow",!0),t),watch:{carIndex:function e(t,n){if(3<=this.carIndex)return this.carIndex=1},answer1:function e(t,n){return console.log("answer1 changed:",t),"undefined"!=typeof q1&&null!==q1&&q1(t),this.white=3!==t},answer2:function e(t,n){if(console.log("answer2 changed:",t),"undefined"!=typeof q2&&null!==q2)return q2(t)},"answer3.c1":function e(t,n){return this.answer3Change(t,n)},"answer3.c2":function e(t,n){return this.answer3Change(t,n)},"answer3.c3":function e(t,n){return this.answer3Change(t,n)},"answer3.c4":function e(t,n){return this.answer3Change(t,n)},nickname:function e(t,n){var o,a,s,r;if(this.nickname=this.nickname.replace(/[\r\n]/g,""),10<this.nickname.length){for(r="",o=0,a=(s=this.nickname.split("")).length;o<a&&!(10<=(r+=i=s[o]).length);o++);return this.nickname=r,!1;//alert "字数限制10个中文字符20个英文字符" 
}},message:function e(t,n){var i,o,a,s;for(4<(s=t.split("\n")).length&&(this.message=this.message.replace(/^\s+|\s+$/g,"")),i=0,o=s.length;i<o;i++)if(32<(a=s[i]).gblen())return this.message=n}},methods:{runHand:function e(){var t=this,n,i,o,a;return!!this.allow&&(n=document.getElementsByClassName("home-handbag")[0],i=.5<Math.random(),n.className="home-handbag ".concat(i?"right":"left"),a=2+Math.floor(8*Math.random()),o=1,TweenMax.set(n,{y:Math.random()*TrueH*.3}),TweenMax.to(n,1,{x:i?-TrueW/3:TrueW/3}),TweenMax.to(n,.2,{yoyo:!0,rotation:5,repeat:a,transformOrigin:i?"right bottom":"left bottom",delay:1,onComplete:function e(){return TweenMax.to(n,.5,{rotation:0}),TweenMax.to(n,.5,{x:0,onComplete:function e(){return setTimeout(function(){return t.runHand()},200+1e3*Math.random())}})}}))},send:function e(t,n){var i=this,o=!(1<arguments.length&&void 0!==n)||n;return this.noteShow=!0,this.noteText=t,this.noteType=o,clearTimeout(this.noteTime),this.noteTime=setTimeout(function(){return i.noteShow=!1},2e3)},answer3Change:function e(t,n){if(console.log("answer3 changed."),"undefined"!=typeof q3&&null!==q3)return q3([this.answer3.c1,this.answer3.c2,this.answer3.c3,this.answer3.c4])},messageShow:function e(){return this.messageInput=!0,document.getElementById("message").focus(),document.getElementById("message").select()},messageFoucs:function e(){return""===this.message&&(this.messageInput=!0),console.log("focus")},messageBlur:function e(){if(""===this.message)return this.messageInput=!1},messageSelectLeft:function e(){if(this.messageIndex--,this.messageIndex<=1)return this.messageIndex=1},messageSelectRight:function e(){if(this.messageIndex++,this.messageIndex>=this.messageList.length)return this.messageIndex=this.messageList.length},over:function e(){var t=this;return this.questionShow=!1,ugc.init(),setTimeout(function(){return t.gameEnd=!0},2e3)},regame:function e(){return window.location.reload()},dateText:function e(t){var n;return console.log(t.replace(/-/g,"/")),(n=new Date(t.replace(/-/g,"/"))).getFullYear()+"年"+(n.getMonth()+1)+"月"+n.getDate()+"日"},goUGC:function e(){return this.lotteryShow=!0},sharePost:function e(t){// @.ugc = ugc.app.view.toDataURL()
return this.gameEnd=!0,ugc.app.renderer.render(ugc.app.stage),this.ugc=t},restart:function e(){return window.location.reload()},goshare:function e(){
// goShare()
return this.share()},share:function e(){return goFinal2(),this.formBoxShow=!1,this.registerShow=!1,this.lotteryShow=!1,console.log("run share"),// ugc.qrcode.visible = true
ugc.app.renderer.render(ugc.app.stage),this.ugc=ugc.app.view.toDataURL(),ugc.buildUGC(ugc.app.view.toDataURL())},callShare:function e(t){var n,i,o;return null!=t&&(this.ugc=t),o=this.ugc,this.wy?(n={image:o,folder:i="drawboard"},this.folder=i,null==o?this.faild():!this.pushed&&(null!=this.shareImageLink?(this.pushed=!1,this.loading=!1,// ugc.back()
neteaseShareImage(),"undefined"!=typeof shareDone&&null!==shareDone&&shareDone(),!0):axios.post(imageurl,n).then(function(e){return 200===e.data.code?main.success(e.data):main.faild(e)}).catch(function(e){
// alert e
return main.faild(e)}))):this.ugcShow=!0},
// ugc.back()
// ugc.qrcode.visible = false
success:function e(t){return this.shareImageLink=t.info,this.pushed=!1,this.loading=!1,// ugc.back()
neteaseShareImage(),shareDone()},
// 抽奖
// unless @.giveUp
// 	setTimeout =>
// 		@.getLottery()
// 	,5000
closeUGC:function e(){return this.ugcShow=!1,shareDone()},faild:function e(t){return this.pushed=!1,this.loading=!1},openSong:function e(){var t;// CloudMusic.song(id[resultNum])
return t=[169794,166317,112678,144143,64497,163639,28853351,153476,5271858,186980,170749,5276250,27591641,32922491,144380,5250828,28785688,186272,210866,555984413],window.location.href="https://music.163.com/#/song?id=".concat(t[resultNum])},openMusic:function e(t){
// goList()
// _public.$children[0].pause()
return CloudMusic.isInApp()?CloudMusic.playlist(t):window.location.href="https://music.163.com/#/playlist?id=".concat(t)},openInApp:function e(){return CloudMusic.open("https://m.giccoo.com/draw-board/")},goNext:function e(){return this.videoStop(),this.pageIndex=2,clearInterval(_startCache)},goShow:function e(){return""===this.nickname?this.send("请输入您的昵称"):(this.pageIndex=2,this.formShow=!0,goFinal1())},goNickname:function e(){return clearInterval(_startCache),this.pageIndex=3},
// @.carIndex = Math.floor(Math.random()*2+1)
goSubmit:function e(){var t=this,n;return n={username:this.nickname,mobile:this.mobile},axios.post("".concat(apiLink,"active/autoSave/insert/database/draw/"),n).then(function(e){return 200===e.data.code?(t.send("恭喜您预约成功"),t.formBoxShow=!1,setTimeout(function(){return t.share()},2e3)):t.send(e.data.reason)}).catch(function(e){return console.log("err:",e),t.send("请求错误,请重试")})},goWeb:function e(){return window.location.href="https://tharu.svw-volkswagen.com/"},focusEvt:function e(t){
// document.getElementById("mobile").scrollIntoViewIfNeeded()
return console.log("height:",document.body.scrollHeight,t)},
// _startCache = setInterval =>
// 	document.body.scrollTop = document.body.scrollHeight
// ,100
blurEvt:function e(t){return clearInterval(_startCache)},videoplay:function e(t){if(console.log("videoPlay",t),this.bgmPlay=_public.$children[0].playing,t.playing)return _public.$children[0].pause()},videoStop:function e(){return this.$children[0].stop()},videoPause:function e(){if(this.bgmPlay)return _public.$children[0].play()}},mounted:function e(){var t,n;// _startCache = setInterval =>
// 	@.carIndex++
// ,2500
return this.carIndex=Math.floor(2*Math.random()+1),console.log(this.carIndex),TrueH=document.documentElement.clientHeight,TrueW=document.documentElement.clientWidth,"NeteaseMusic"===sys&&(this.wy=!0),t=2*TrueH*(2-2*TrueW/750+.01),// game = new Game({el: "game",h: h})
this.wy=CloudMusic.isInApp(),n=CloudMusic.getClientVersion().split(".")}})},chnNumChar=["零","一","二","三","四","五","六","七","八","九"],chnUnitSection=["","万","亿","万亿","亿亿"],chnUnitChar=["","十","百","千"],SectionToChinese=function e(t){var n,i,o,a,s,r;for(n=o="",i=t,r=!(a=0);0<t;)0===(s=t%10)?r||(r=!0,n=chnNumChar[s]+n):(r=!1,o=chnNumChar[s],n=(o+=chnUnitChar[a])+n),a++,t=Math.floor(t/10);return 10<=i&&i<20?n.substr(1):n},NumberToChinese=function e(t){var n,i,o,a,s;if(n=a="",i=!1,(s=0)===t)return chnNumChar[0];for(;0<t;)o=t%1e4,i&&(n=chnNumChar[0]+n),a=SectionToChinese(o),n=(a+=0!==o?chnUnitSection[s]:chnUnitSection[0])+n,i=o<1e3&&0<o,t=Math.floor(t/1e4),s++;return n},tryThis=function e(t){return console.log("msg:",t)};
//# sourceMappingURL=main.js.map