// Generated by CoffeeScript 1.9.1
var ANIMATION_END_NAME, ANIMATION_END_NAMES, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, css3Prefix, i, imgs, j, len, loadAllImage, loadComper, loadFinished, mTestElement;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

imgs = [];

window.onload = function() {
  var MK;
  riot.mount("*");
  setTimeout(function() {
    return loadAllImage();
  }, 500);
  MK = $("body").width() / $("body").height();
  if ($("body").height() <= 460 || MK > 0.65) {
    return $("body").addClass("iphone4");
  }
};

loadAllImage = function() {
  var imageList, max;
  max = $("img[data-src]").length;
  imageList = $("img[data-src]").length;
  console.log(max);
  return $("img[data-src]").each(function(i) {
    var img;
    img = $(this)[0];
    img.onload = function() {
      max--;
      loadComper(parseInt((imageList - max) / imageList * 100));
      if (max <= 0) {
        return loadFinished();
      }
    };
    img.src = $(this).attr("data-src");
    return imgs.push(img);
  });
};

loadComper = function(m) {};

loadFinished = function() {
  return $(".loading").removeClass("loaded");
};
