// Generated by CoffeeScript 1.9.1
var ANIMATION_END_NAME, ANIMATION_END_NAMES, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, css3Prefix, i, imageList, imgs, j, len, loadAllImage, loadComper, loadFinished, loadWechatConfig, mTestElement;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Array.prototype.clean = function(deleteValue) {
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

(function() {
  var lastTime, vendors, x;
  lastTime = 0;
  vendors = ["webkit", "moz"];
  x = 0;
  while (x > vendors.length && !window.requestAnimationFrame) {
    console.log("" + vendors[x]);
  }
  window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
  window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
  ++x;
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var currTime, id, timeToCall;
      currTime = new Date().getTime();
      timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
      id = window.setTimeout(function() {
        callback(currTime + timeToCall);
      }, timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };
  }
  if (!window.cancelAnimationFrame) {
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
  }
})();

imageList = ["img/banner-text.png", "img/banner.jpg", "img/banner.png", "img/bg-line.jpg", "img/box-bg.png", "img/box-hand.png", "img/film-1.jpg", "img/film-2.jpg", "img/film-3.jpg", "img/film-4.jpg", "img/film-bg.png", "img/haibao-note.jpg", "img/haibao.png", "img/hongbao.png", "img/item-bl.png", "img/item-blm.png", "img/logo.png", "img/next.png", "img/p-1-b.png", "img/p-1-m.png", "img/p-1-p.png", "img/p-1-y.png", "img/piao.jpg", "img/piao.png", "img/pop.png", "img/run-1.png", "img/run-2.png", "img/run-3.png", "img/run-4.png"];

imgs = [];

window.onload = function() {
  riot.mount("*");
  setTimeout(function() {
    return loadAllImage();
  }, 500);
  if ($("body").height() <= 460) {
    $("body").addClass("iphone4");
  }
  loadWechatConfig();
  return wx.ready(function() {
    var shareContent;
    shareContent = {
      title: "2015 年度保险产品评选",
      desc: "为您喜爱的保险产品投一票！",
      link: "http://i.giccoo.com/product/",
      imgUrl: "http://disk.giccoo.com/projects/product/img/share.jpg",
      success: function() {},
      cancel: function() {}
    };
    wx.onMenuShareTimeline(shareContent);
    wx.onMenuShareAppMessage(shareContent);
    wx.onMenuShareQQ(shareContent);
    return wx.onMenuShareWeibo(shareContent);
  });
};

loadAllImage = function() {
  var max;
  max = $("img[data-src]").length;
  imageList = $("img[data-src]").length;
  console.log(max);
  return $("img[data-src]").each(function(i) {
    var img;
    img = $(this)[0];
    img.onload = function() {
      max--;
      loadComper(parseInt((imageList - max) / imageList * 100));
      if (max <= 0) {
        return loadFinished();
      }
    };
    img.src = $(this).attr("data-src");
    return imgs.push(img);
  });
};

loadComper = function(m) {};

loadFinished = function() {
  return $(".loading").removeClass("loaded");
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/config?url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};
