// Generated by CoffeeScript 1.9.1
var ANIMATION_END_NAME, ANIMATION_END_NAMES, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, css3Prefix, hidePage, i, imageList, imgs, j, len, loadAllImage, loadComper, loadFinished, mTestElement, starEat, tags;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Array.prototype.clean = function(deleteValue) {
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

(function() {
  var lastTime, vendors, x;
  lastTime = 0;
  vendors = ["webkit", "moz"];
  x = 0;
  while (x > vendors.length && !window.requestAnimationFrame) {
    console.log("" + vendors[x]);
  }
  window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
  window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
  ++x;
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var currTime, id, timeToCall;
      currTime = new Date().getTime();
      timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
      id = window.setTimeout(function() {
        callback(currTime + timeToCall);
      }, timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };
  }
  if (!window.cancelAnimationFrame) {
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
  }
})();

imageList = ["img/button-eat.png", "img/button-info.png", "img/button-list.png", "img/button-random.png", "img/home-bg.jpg", "img/home-logo.png", "img/home-text.png", "img/icon-back.png", "img/icon-play.png", "img/icon-save.png", "img/icon-star.png", "img/logo.png", "img/select-line.png", "img/start.png", "img/wechat.png", "img/box.png", "img/cuisine-1.png", "img/cuisine-2.png", "img/cuisine-3.png", "img/cuisine-4.png", "img/cuisine-5.png", "img/cuisine-6.png", "img/cuisine-7.png", "img/cuisine-8.png", "img/cuisine-9.png", "img/cuisine-10.png"];

imgs = [];

window.onload = function() {
  setTimeout(function() {
    return loadAllImage();
  }, 500);
  if ($("body").height() <= 460) {
    $("body").addClass("i4");
  }
  return $(".wechat").on("click", function() {
    return $(".wechat").hide();
  });
};

loadAllImage = function() {
  var image, img, k, len1, max, results;
  max = imageList.length;
  results = [];
  for (k = 0, len1 = imageList.length; k < len1; k++) {
    image = imageList[k];
    img = new Image();
    img.onload = function() {
      max--;
      loadComper(parseInt((imageList.length - max) / imageList.length * 100));
      if (max <= 0) {
        return loadFinished();
      }
    };
    img.src = image;
    results.push(imgs.push(img));
  }
  return results;
};

loadComper = function(m) {
  return $("#loading-text").text(m);
};

tags = null;

loadFinished = function() {
  tags = riot.mount("*");
  $(".loading").addClass("fadeOut animated");
  return setTimeout(function() {
    $(".loading").hide();
    return $(".homepage").show();
  }, 500);
};

hidePage = function() {
  $(".homepage").addClass("fadeOut animated");
  return setTimeout(function() {
    $(".homepage").hide();
    return $(".otherpage").show();
  }, 500);
};

starEat = function() {
  $(".infopage").removeClass("fadeIn").addClass("fadeOut animated");
  return setTimeout(function() {
    $(".infopage").hide();
    $(".select-page").show();
    return tags[1].init();
  }, 500);
};
