// Generated by CoffeeScript 1.10.0
var ANIMATION_END_NAME, ANIMATION_END_NAMES, CompanyPage, Done, POST, SendNote, TRANSITION_END_NAME, TRANSITION_END_NAMES, UpdateShare, VENDORS, _POSTING, _QA, _QUESTION, _QUESTION_COMPANY, _citys, _jplink, company, css3Prefix, hideFocus, hideShare, i, j, len, loadEnd, loadStart, loadWechatConfig, mTestElement, showFocus, showShare;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Array.prototype.clean = function(deleteValue) {
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

_citys = {};

_citys["请选择"] = ["请选择"];

_citys["保险集团控股公司"] = [];

_citys["保险集团控股公司"].push("中国人民保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国太平保险集团有限责任公司");

_citys["保险集团控股公司"].push("中国人寿保险（集团）公司");

_citys["保险集团控股公司"].push("安邦保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国再保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("阳光保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国太平洋保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("中华联合保险控股股份有限公司");

_citys["保险集团控股公司"].push("中国平安保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("富德保险控股股份有限公司");

_citys["保险集团控股公司"].push("华泰保险集团股份有限公司");

_citys["保险公司－人身险"] = [];

_citys["保险公司－人身险"].push("中国人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中国太平洋人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中国平安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("新华人寿保险股份有限公司");

_citys["保险公司－人身险"].push("泰康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("太平人寿保险有限公司");

_citys["保险公司－人身险"].push("中宏人寿保险有限公司");

_citys["保险公司－人身险"].push("建信人寿保险有限公司");

_citys["保险公司－人身险"].push("中德安联人寿保险有限公司");

_citys["保险公司－人身险"].push("工银安盛人寿保险有限公司");

_citys["保险公司－人身险"].push("友邦保险有限公司江门支公司");

_citys["保险公司－人身险"].push("友邦保险有限公司东莞支公司");

_citys["保险公司－人身险"].push("北大方正人寿保险有限公司");

_citys["保险公司－人身险"].push("中荷人寿保险有限公司");

_citys["保险公司－人身险"].push("中英人寿保险有限公司");

_citys["保险公司－人身险"].push("同方全球人寿保险有限公司");

_citys["保险公司－人身险"].push("民生人寿保险股份有限公司");

_citys["保险公司－人身险"].push("招商信诺人寿保险有限公司");

_citys["保险公司－人身险"].push("长生人寿保险有限公司");

_citys["保险公司－人身险"].push("恒安标准人寿保险有限公司");

_citys["保险公司－人身险"].push("中美联泰大都会人寿保险有限公司");

_citys["保险公司－人身险"].push("平安健康保险股份有限公司");

_citys["保险公司－人身险"].push("中国人民健康保险股份有限公司");

_citys["保险公司－人身险"].push("华夏人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中银三星人寿保险有限公司");

_citys["保险公司－人身险"].push("君康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("信泰人寿保险股份有限公司");

_citys["保险公司－人身险"].push("农银人寿保险股份有限公司");

_citys["保险公司－人身险"].push("长城人寿保险股份有限公司");

_citys["保险公司－人身险"].push("昆仑健康保险股份有限公司");

_citys["保险公司－人身险"].push("新光海航人寿保险有限责任公司");

_citys["保险公司－人身险"].push("汇丰人寿保险有限公司");

_citys["保险公司－人身险"].push("君龙人寿保险有限公司");

_citys["保险公司－人身险"].push("百年人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中邮人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中融人寿保险股份有限公司");

_citys["保险公司－人身险"].push("安邦人寿保险股份有限公司");

_citys["保险公司－人身险"].push("利安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("华汇人寿保险股份有限公司");

_citys["保险公司－人身险"].push("前海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("信诚人寿保险有限公司");

_citys["保险公司－人身险"].push("交银康联人寿保险有限公司");

_citys["保险公司－人身险"].push("天安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中意人寿保险有限公司");

_citys["保险公司－人身险"].push("光大永明人寿保险有限公司");

_citys["保险公司－人身险"].push("友邦保险有限公司北京分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司上海分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司江苏分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司广东分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司深圳分公司");

_citys["保险公司－人身险"].push("瑞泰人寿保险有限公司");

_citys["保险公司－人身险"].push("富德生命人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中美大都会人寿保险有限公司");

_citys["保险公司－人身险"].push("东方人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中法人寿保险有限责任公司");

_citys["保险公司－人身险"].push("平安养老保险股份有限公司");

_citys["保险公司－人身险"].push("合众人寿保险股份有限公司");

_citys["保险公司－人身险"].push("华泰人寿保险股份有限公司");

_citys["保险公司－人身险"].push("陆家嘴国泰人寿保险有限责任公司");

_citys["保险公司－人身险"].push("太平养老保险股份有限公司");

_citys["保险公司－人身险"].push("和谐健康保险股份有限公司");

_citys["保险公司－人身险"].push("中国人民人寿保险股份有限公司");

_citys["保险公司－人身险"].push("国华人寿保险股份有限公司");

_citys["保险公司－人身险"].push("恒大人寿保险有限公司");

_citys["保险公司－人身险"].push("中国人寿养老保险股份有限公司");

_citys["保险公司－人身险"].push("长江养老保险股份有限公司");

_citys["保险公司－人身险"].push("英大泰和人寿保险股份有限公司");

_citys["保险公司－人身险"].push("泰康养老保险股份有限公司");

_citys["保险公司－人身险"].push("幸福人寿保险股份有限公司");

_citys["保险公司－人身险"].push("阳光人寿保险股份有限公司");

_citys["保险公司－人身险"].push("上海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("东吴人寿保险股份有限公司");

_citys["保险公司－人身险"].push("弘康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("吉祥人寿保险股份有限公司");

_citys["保险公司－人身险"].push("复星保德信人寿保险有限公司");

_citys["保险公司－人身险"].push("中韩人寿保险有限公司");

_citys["保险公司－人身险"].push("德华安顾人寿保险有限公司");

_citys["保险公司－人身险"].push("安邦养老保险股份有限公司");

_citys["保险公司－人身险"].push("太保安联健康保险股份有限公司");

_citys["保险公司－人身险"].push("渤海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("国联人寿保险股份有限公司");

_citys["保险公司－财产险"] = [];

_citys["保险公司－财产险"].push("中国人民财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国大地财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国出口信用保险公司");

_citys["保险公司－财产险"].push("中华联合财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国太平洋财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国平安财产保险股份有限公司");

_citys["保险公司－财产险"].push("天安财产保险股份有限公司");

_citys["保险公司－财产险"].push("史带财产保险股份有限公司");

_citys["保险公司－财产险"].push("华安财产保险股份有限公司");

_citys["保险公司－财产险"].push("永安财产保险股份有限公司");

_citys["保险公司－财产险"].push("安联财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("日本财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("利宝保险有限公司");

_citys["保险公司－财产险"].push("安信农业保险股份有限公司");

_citys["保险公司－财产险"].push("中航安盟财产保险有限公司");

_citys["保险公司－财产险"].push("永诚财产保险股份有限公司");

_citys["保险公司－财产险"].push("安华农业保险股份有限公司");

_citys["保险公司－财产险"].push("安盛天平财产保险股份有限公司");

_citys["保险公司－财产险"].push("阳光财产保险股份有限公司");

_citys["保险公司－财产险"].push("阳光农业相互保险公司");

_citys["保险公司－财产险"].push("爱和谊日生同和财产保险（中国）");

_citys["保险公司－财产险"].push("国元农业保险股份有限公司");

_citys["保险公司－财产险"].push("鼎和财产保险股份有限公司");

_citys["保险公司－财产险"].push("中煤财产保险股份有限公司");

_citys["保险公司－财产险"].push("国泰财产保险有限责任公司");

_citys["保险公司－财产险"].push("英大泰和财产保险股份有限公司");

_citys["保险公司－财产险"].push("紫金财产保险股份有限公司");

_citys["保险公司－财产险"].push("日本兴亚财产保险（中国）有限责任公司");

_citys["保险公司－财产险"].push("浙商财产保险股份有限公司");

_citys["保险公司－财产险"].push("信达财产保险股份有限公司");

_citys["保险公司－财产险"].push("富德财产保险股份有限公司");

_citys["保险公司－财产险"].push("鑫安汽车保险股份有限公司");

_citys["保险公司－财产险"].push("北部湾财产保险股份有限公司");

_citys["保险公司－财产险"].push("众安在线财产保险股份有限公司");

_citys["保险公司－财产险"].push("华海财产保险股份有限公司");

_citys["保险公司－财产险"].push("燕赵财产保险股份有限公司");

_citys["保险公司－财产险"].push("太平财产保险有限公司");

_citys["保险公司－财产险"].push("民安财产保险有限公司");

_citys["保险公司－财产险"].push("美亚财产保险有限公司");

_citys["保险公司－财产险"].push("东京海上日动火灾保险（中国）有限公司");

_citys["保险公司－财产险"].push("安盛保险有限公司");

_citys["保险公司－财产险"].push("瑞再企商保险有限公司");

_citys["保险公司－财产险"].push("丘博保险（中国）有限公司");

_citys["保险公司－财产险"].push("三井住友海上火灾保险（中国）有限公司");

_citys["保险公司－财产险"].push("三星财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("中银保险有限公司");

_citys["保险公司－财产险"].push("都邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("渤海财产保险股份有限公司");

_citys["保险公司－财产险"].push("华农财产保险股份有限公司");

_citys["保险公司－财产险"].push("苏黎世财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("中国人寿财产保险股份有限公司");

_citys["保险公司－财产险"].push("安诚财产保险股份有限公司");

_citys["保险公司－财产险"].push("现代财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("长安责任保险股份有限公司");

_citys["保险公司－财产险"].push("劳合社保险（中国）有限公司");

_citys["保险公司－财产险"].push("中意财产保险有限公司");

_citys["保险公司－财产险"].push("有限公司乐爱金财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("富邦财产保险有限公司");

_citys["保险公司－财产险"].push("信利保险（中国）有限公司");

_citys["保险公司－财产险"].push("泰山财产保险股份有限公司");

_citys["保险公司－财产险"].push("锦泰财产保险股份有限公司");

_citys["保险公司－财产险"].push("众诚汽车保险股份有限公司");

_citys["保险公司－财产险"].push("华泰财产保险有限公司");

_citys["保险公司－财产险"].push("长江财产保险股份有限公司");

_citys["保险公司－财产险"].push("诚泰财产保险股份有限公司");

_citys["保险公司－财产险"].push("安邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("恒邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("合众财产保险股份有限公司");

_citys["保险公司－财产险"].push("中路财产保险股份有限公司");

_citys["保险公司－财产险"].push("中原农业保险股份有限公司");

_citys["保险公司－财产险"].push("中国铁路财产保险自保有限公司");

_citys["再保险公司"] = [];

_citys["再保险公司"].push("中国财产再保险有限责任公司");

_citys["再保险公司"].push("中国人寿再保险有限责任公司");

_citys["再保险公司"].push("瑞士再保险股份有限公司北京分公司");

_citys["再保险公司"].push("慕尼黑再保险公司北京分公司");

_citys["再保险公司"].push("德国通用再保险股份公司上海分公司");

_citys["再保险公司"].push("法国再保险公司北京分公司");

_citys["再保险公司"].push("汉诺威再保险股份公司上海分公司");

_citys["再保险公司"].push("太平再保险有限公司");

_citys["再保险公司"].push("RGA美国再保险公司上海分公司");

_citys["保险资产管理公司"] = [];

_citys["保险资产管理公司"].push("中国人保资产管理股份有限公司");

_citys["保险资产管理公司"].push("中国人寿资产管理有限公司");

_citys["保险资产管理公司"].push("华泰资产管理有限公司");

_citys["保险资产管理公司"].push("平安资产管理有限责任公司");

_citys["保险资产管理公司"].push("中再资产管理股份有限公司");

_citys["保险资产管理公司"].push("泰康资产管理有限责任公司");

_citys["保险资产管理公司"].push("太平洋资产管理有限责任公司");

_citys["保险资产管理公司"].push("太平资产管理有限公司");

_citys["保险资产管理公司"].push("新华资产管理股份有限公司");

_citys["保险资产管理公司"].push("安邦资产管理有限责任公司");

_citys["保险资产管理公司"].push("华夏久盈资产管理有限责任公司	");

_citys["保险资产管理公司"].push("生命保险资产管理有限公司");

_citys["保险资产管理公司"].push("光大永明资产管理股份有限公司");

_citys["保险资产管理公司"].push("合众资产管理股份有限公司");

_citys["保险资产管理公司"].push("民生通惠资产管理有限公司");

_citys["保险资产管理公司"].push("阳光资产管理股份有限公司");

_citys["保险资产管理公司"].push("中英益利资产管理股份有限公司");

_citys["保险资产管理公司"].push("中意资产管理有限责任公司");

_citys["保险资产管理公司"].push("华安财保资产管理有限责任公司");

_citys["保险资产管理公司"].push("长城财富资产管理股份有限公司");

_citys["保险资产管理公司"].push("英大保险资产管理有限公司");

_QA = null;

_QUESTION = [
  {
    id: 1,
    question: "对于保险的理解，下面哪句话是错的？",
    size: "big",
    answers: ["保险是一种未雨绸缪的智慧", "保险体现人们的互助精神", "为家人购买保险是对家庭的关爱", "保险和慈善是一回事"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-1.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 2,
    question: "关于保险的功能，哪一项是错的？",
    size: "big",
    answers: ["损失补偿功能", "无偿救济功能", "投资功能", "储蓄功能"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-2.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 3,
    question: "关于保险公司收取保费的依据，哪一项是错的？",
    size: "big",
    answers: ["如保障对象是人，要考虑年龄、性别、婚姻状况、身体状况、工作状况等。", "如保障对象是财产，要考虑其本身价值、使用年限、用途、所处位置等。", "保险标的风险高保费就较高", "保费收取没有严格依据"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-1.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 4,
    question: "消费者购买家庭财产保险，通常情况下，对于以下哪种标的，保险公司不予承保？",
    size: "big",
    answers: ["家具", "室内装饰物", "食品", "家用电器"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-2.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 5,
    question: "以下关于机动车辆保险，哪种说法不正确？",
    size: "big",
    answers: ["所有机动车辆必须购买交强险", "基本险包括机动车辆损失保险和机动车第三者责任保险", "附加险包括全车盗抢险、玻璃单独破碎险、车身划痕损失险等", "买了交强险就不用购买其他机动车辆保险了"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-1.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 6,
    question: "关于重大疾病保险与医疗保险，下列哪种表述是错误的？",
    size: "big",
    answers: ["尽量选择保障范围广的重大疾病保险", "重大疾病保险和医疗保险是一回事", "医疗保险是按实际所用医疗费来赔付", "重大疾病保险是定额赔付，不考虑实际支出多少医疗费"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-2.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 7,
    question: "分红险是指保险公司在每个会计年度结束后，将上一会计年度该类分红保险的可分配盈余，按照一定比例、以现金红利或增额红利的方式，分配给客户的一种人寿保险。以下说法那种是错误的？",
    size: "normal",
    answers: ["分红多少取决于保费投入多少以及产品选择的不同", "分红险是一种人寿保险", "购买分红险的客户承担一定的投资风险", "买了分红险一定可以年年收红利"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-1.jpg",
    link: "http://e.cic.cn/"
  }, {
    id: 8,
    question: "消费者购买保险产品，除了通过保险营销员、保险公司还有其他渠道，具体来说，不可以通过哪种途径购买保险？",
    size: "big",
    answers: ["保险代理公司", "保险公估公司", "保险经纪公司", "互联网渠道"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-2.jpg",
    link: "http://www.baidu.com"
  }, {
    id: 9,
    question: "全国保险消费者投诉维权热线电话是？",
    size: "big",
    answers: ["12378", "12306", "12315", "12310"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-9.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 10,
    question: "消费者在行使自己保险索赔权利，要求保险公司进行赔偿时，受到时间的限制。人寿保险的被保险人或者受益人向保险人请求给付保险金的诉讼时效为多长时间？",
    size: "normal",
    answers: ["60天", "一年", "两年", "五年"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-normal-10.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }
];

_QUESTION_COMPANY = [
  {
    id: 1,
    question: "下列那些风险是不可保的？",
    size: "big",
    answers: ["生病", "车辆损失", "房屋损失", "股票投资"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-1.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 2,
    question: "投保人或者被保险人变更受益人，当事人主张变更行为自变更意思表示发出时生效的，人民法院（）。 投保人或者被保险人变更受益人未通知保险人，保险人主张变更对其不发生效力的，人民法院（）。以上两处均正确的是?",
    size: "small",
    answers: ["应予支持 不予支持", "不予支持 应予支持", "不予支持 不予支持", "应予支持 应予支持"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-2.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 3,
    question: "下列哪项不是保险的本质？",
    size: "big",
    answers: ["保险是用今天的钱筹划明天的生活", "保险是用大钱换小钱", "保险是仁爱的化身，是责任的体现", "保险是一种赌博，以今天的平安赌明天的风险"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-3.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 4,
    question: "下列哪些不属于分红保险产品的主要特征？",
    size: "big",
    answers: ["保单持有人享受经营成果", "客户承担一定的投资风险", "定价的精算假设比较激进", "保险给付、退保金中含有红利"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-4.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 5,
    question: "保险合同约定按照基本医疗保险的标准核定医疗费用，保险人以被保险人的医疗支出超出基本医疗保险范围为由拒绝给付保险金的，人民法院（）；保险人有证据证明被保险人支出的费用超过基本医疗保险同类医疗费用标准，要求对超出部分拒绝给付保险金的，人民法院（）。以上两处均正确的是?",
    size: "small",
    answers: ["应予支持 不予支持", "不予支持 应予支持", "不予支持 不予支持", "应予支持 应予支持"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-5.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 6,
    question: "保险是金融业的三驾马车之一，在经济发展中具有举足轻重的地位，下列哪项不是其具体表现？",
    size: "big",
    answers: ["刺激消费", "不利于拉动投资", "支持对外贸易", "促进技术创新"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-6.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 7,
    question: "2012年6月24日，中国“蛟龙”号载人潜水器在西太平洋的马里亚纳海沟试验海区首次突破7000米，创造了中国载人深潜的历史记录。同时，我国也开创了首例探潜器保险，引入了4家保险公司以及海外再保险人。该项目采用了何种机制来减少和避免巨大损失？",
    size: "small",
    answers: ["风险分散机制", "风险管理机制", "产业链整合机制", "资金融通机制"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-7.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 8,
    question: "保险人以被保险人自杀为由拒绝给付保险金的，由（）承担举证责任。受益人或者被保险人的继承人以被保险人自杀时无民事行为能力为由抗辩的，由（）承担举证责任。以上两空格处均正确的是?",
    size: "normal",
    answers: ["保险人、保险人", "受益人或者被保险人的继承人、保险人 ", "保险人、受益人或者被保险人的继承人 ", "受益人或者被保险人的继承人、受益人或者被保险人的继承人保险人"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-8.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 9,
    question: "保险合同效力中止后，经保险人与投保人协商并达成协议，在投保人补交保险费后，合同效力恢复。但自合同效力中止之日起（）双方未达成协议的，保险人有权解除合同。",
    size: "normal",
    answers: ["满一年", "满两年", "满三年", "满四年"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-9.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }, {
    id: 10,
    question: "保险业防范和化解风险的最后一道防线是( )",
    size: "big",
    answers: ["中国保险监督管理委员会", "再保险公司", "保险保障基金", "保险投资基金"],
    banner: "http://disk.giccoo.com/projects/qa/img/banner-company-10.jpg",
    link: "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5"
  }
];

company = null;

_jplink = "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5";

loadStart = function() {
  var count, ep, now;
  count = $("[data-src]").length;
  now = 0;
  ep = $("#loading-text");
  return $("[data-src]").each(function() {
    var img;
    img = new Image();
    img.onload = function() {
      now++;
      ep.text(parseInt(now / count * 100));
      if (now >= count) {
        return loadEnd();
      }
    };
    img.src = $(this).attr("data-src");
    $(this).after(img);
    return $(this).remove();
  });
};

loadEnd = function() {
  riot.mount("#select-company", "select-company");
  riot.mount("#qa", "qa");
  $(".loading").addClass("fadeOut animated");
  return setTimeout(function() {
    return $(".loading").remove();
  }, 520);
};

window.onload = function() {
  var MK;
  if (openid === "" && project === "qa") {
    window.location.href = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxb3dd8b8d67e940c4&redirect_uri={url}&response_type=code&scope=snsapi_base&state=123#wechat_redirect".replace("{url}", encodeURIComponent("http://i.giccoo.com/" + project + "/"));
    return false;
  }
  if (openid === "" && project === "question") {
    window.location.href = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxe2f2c38eb9ac51c7&redirect_uri={url}&response_type=code&scope=snsapi_base&state=123#wechat_redirect".replace("{url}", encodeURIComponent("http://i.giccoo.com/" + project + "/"));
    return false;
  }
  riot.mount("#pages", "pages");
  MK = $("body").width() / $("body").height();
  if ($("body").height() <= 460 || MK > 0.65) {
    $("body").addClass("iphone4");
  }
  $(".page.info-page .btn-join").click(function() {
    $(".page.info-page").removeClass("on");
    return $(".page.select-page").addClass("on");
  });
  $(".page.select-page .btn-join").click(function() {
    $(".page.select-page").removeClass("on");
    return $(".page.note-page").addClass("on");
  });
  loadWechatConfig();
  return wx.ready(function() {
    var shareContent;
    shareContent = {
      title: SHARETITLE,
      desc: SHAREDESC,
      link: SHARELINK,
      imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
      success: function() {},
      cancel: function() {}
    };
    wx.onMenuShareTimeline(shareContent);
    wx.onMenuShareAppMessage(shareContent);
    wx.onMenuShareQQ(shareContent);
    return wx.onMenuShareWeibo(shareContent);
  });
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/config?url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};

UpdateShare = function(text) {
  var TimelineShareContent;
  TimelineShareContent = {
    title: text,
    desc: SHAREDESC,
    link: SHARELINK,
    imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
    success: function() {},
    cancel: function() {}
  };
  wx.onMenuShareTimeline(TimelineShareContent);
  wx.onMenuShareAppMessage(TimelineShareContent);
  wx.onMenuShareQQ(TimelineShareContent);
  return wx.onMenuShareWeibo(TimelineShareContent);
};

showFocus = function() {
  return $(".pop.focus-page").addClass("on");
};

hideFocus = function() {
  return $(".pop.focus-page").removeClass("on");
};

CompanyPage = function(name) {
  company = name;
  if (_QA != null) {
    _QA.changeCompany();
  }
  $(".pop.select-company").removeClass("on");
  $(".page.note-page").removeClass("on");
  return $(".page.question-page").addClass("on");
};

_POSTING = false;

POST = function(answers, callback) {
  var data;
  if (_POSTING) {
    return SendNote("正在提交请稍后...");
  }
  _POSTING = true;
  data = {
    openid: openid,
    answer: answers.join(",")
  };
  if (company != null) {
    data.company = company;
  }
  $(".pop.select-company").removeClass("on");
  return $.post(POSTurl, data, function(msg) {
    _POSTING = false;
    if (msg.recode === 200) {
      SendNote("提交成功");
      return setTimeout(function() {
        return Done(msg);
      }, 3000);
    } else if (msg.recode === 202) {
      SendNote("您已经提交过答案,无法变更,即将显示您本次答题的正确率。", 4000);
      return setTimeout(function() {
        return Done(msg, true);
      }, 4000);
    } else {
      return SendNote(msg.reason);
    }
  });
};

Done = function(msg, secondTime) {
  var fen;
  if (secondTime == null) {
    secondTime = false;
  }
  $(".pop.select-company").removeClass("on");
  fen = msg.info.fen;
  if (msg.info.fen > 20) {
    fen = fen + parseInt(Math.random() * 9);
  } else {
    fen = fen;
  }
  if (fen > 99) {
    fen = 99;
  }
  UpdateShare("恭喜你!保险知识有奖竞赛正确率超过了 " + fen + "% 的网友.");
  $(".page.finished-page #nums").text(fen);
  $(".page").removeClass("on");
  return $(".page.finished-page").addClass("on");
};

showShare = function() {
  return $(".share-box").addClass("on");
};

hideShare = function() {
  return $(".share-box").removeClass("on");
};

SendNote = function(msg, time) {
  if (time == null) {
    time = 3000;
  }
  $("body").append("<note title='" + msg + ("' time='" + time + "'></note>"));
  return riot.mount("note");
};
