// Generated by CoffeeScript 1.10.0
var ANIMATION_END_NAME, ANIMATION_END_NAMES, CompanyPage, Done, POST, SendNote, TRANSITION_END_NAME, TRANSITION_END_NAMES, UpdateShare, VENDORS, _QUESTION, _citys, company, css3Prefix, hideFocus, hideShare, i, j, len, loadEnd, loadStart, loadWechatConfig, mTestElement, showFocus, showShare;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Array.prototype.clean = function(deleteValue) {
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

(function() {
  var lastTime, vendors, x;
  lastTime = 0;
  vendors = ["webkit", "moz"];
  x = 0;
  while (x > vendors.length && !window.requestAnimationFrame) {
    console.log("" + vendors[x]);
  }
  window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
  window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
  ++x;
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var currTime, id, timeToCall;
      currTime = new Date().getTime();
      timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
      id = window.setTimeout(function() {
        callback(currTime + timeToCall);
      }, timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };
  }
  if (!window.cancelAnimationFrame) {
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
  }
})();

_citys = {};

_citys["保险集团控股公司"] = [];

_citys["保险集团控股公司"].push("中国人民保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国太平保险集团有限责任公司");

_citys["保险集团控股公司"].push("中国人寿保险（集团）公司");

_citys["保险集团控股公司"].push("安邦保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国再保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("阳光保险集团股份有限公司");

_citys["保险集团控股公司"].push("中国太平洋保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("中华联合保险控股股份有限公司");

_citys["保险集团控股公司"].push("中国平安保险（集团）股份有限公司");

_citys["保险集团控股公司"].push("富德保险控股股份有限公司");

_citys["保险集团控股公司"].push("华泰保险集团股份有限公司");

_citys["保险公司－人身险"] = [];

_citys["保险公司－人身险"].push("中国人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中国太平洋人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中国平安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("新华人寿保险股份有限公司");

_citys["保险公司－人身险"].push("泰康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("太平人寿保险有限公司");

_citys["保险公司－人身险"].push("中宏人寿保险有限公司");

_citys["保险公司－人身险"].push("建信人寿保险有限公司");

_citys["保险公司－人身险"].push("中德安联人寿保险有限公司");

_citys["保险公司－人身险"].push("工银安盛人寿保险有限公司");

_citys["保险公司－人身险"].push("友邦保险有限公司江门支公司");

_citys["保险公司－人身险"].push("友邦保险有限公司东莞支公司");

_citys["保险公司－人身险"].push("北大方正人寿保险有限公司");

_citys["保险公司－人身险"].push("中荷人寿保险有限公司");

_citys["保险公司－人身险"].push("中英人寿保险有限公司");

_citys["保险公司－人身险"].push("同方全球人寿保险有限公司");

_citys["保险公司－人身险"].push("民生人寿保险股份有限公司");

_citys["保险公司－人身险"].push("招商信诺人寿保险有限公司");

_citys["保险公司－人身险"].push("长生人寿保险有限公司");

_citys["保险公司－人身险"].push("恒安标准人寿保险有限公司");

_citys["保险公司－人身险"].push("中美联泰大都会人寿保险有限公司");

_citys["保险公司－人身险"].push("平安健康保险股份有限公司");

_citys["保险公司－人身险"].push("中国人民健康保险股份有限公司");

_citys["保险公司－人身险"].push("华夏人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中银三星人寿保险有限公司");

_citys["保险公司－人身险"].push("君康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("信泰人寿保险股份有限公司");

_citys["保险公司－人身险"].push("农银人寿保险股份有限公司");

_citys["保险公司－人身险"].push("长城人寿保险股份有限公司");

_citys["保险公司－人身险"].push("昆仑健康保险股份有限公司");

_citys["保险公司－人身险"].push("新光海航人寿保险有限责任公司");

_citys["保险公司－人身险"].push("汇丰人寿保险有限公司");

_citys["保险公司－人身险"].push("君龙人寿保险有限公司");

_citys["保险公司－人身险"].push("百年人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中邮人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中融人寿保险股份有限公司");

_citys["保险公司－人身险"].push("安邦人寿保险股份有限公司");

_citys["保险公司－人身险"].push("利安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("华汇人寿保险股份有限公司");

_citys["保险公司－人身险"].push("前海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("信诚人寿保险有限公司");

_citys["保险公司－人身险"].push("交银康联人寿保险有限公司");

_citys["保险公司－人身险"].push("天安人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中意人寿保险有限公司");

_citys["保险公司－人身险"].push("光大永明人寿保险有限公司");

_citys["保险公司－人身险"].push("友邦保险有限公司北京分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司上海分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司江苏分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司广东分公司");

_citys["保险公司－人身险"].push("友邦保险有限公司深圳分公司");

_citys["保险公司－人身险"].push("瑞泰人寿保险有限公司");

_citys["保险公司－人身险"].push("富德生命人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中美大都会人寿保险有限公司");

_citys["保险公司－人身险"].push("东方人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中法人寿保险有限责任公司");

_citys["保险公司－人身险"].push("平安养老保险股份有限公司");

_citys["保险公司－人身险"].push("合众人寿保险股份有限公司");

_citys["保险公司－人身险"].push("华泰人寿保险股份有限公司");

_citys["保险公司－人身险"].push("陆家嘴国泰人寿保险有限责任公司");

_citys["保险公司－人身险"].push("太平养老保险股份有限公司");

_citys["保险公司－人身险"].push("和谐健康保险股份有限公司");

_citys["保险公司－人身险"].push("中国人民人寿保险股份有限公司");

_citys["保险公司－人身险"].push("国华人寿保险股份有限公司");

_citys["保险公司－人身险"].push("中新大东方人寿保险有限公司");

_citys["保险公司－人身险"].push("中国人寿养老保险股份有限公司");

_citys["保险公司－人身险"].push("长江养老保险股份有限公司");

_citys["保险公司－人身险"].push("英大泰和人寿保险股份有限公司");

_citys["保险公司－人身险"].push("泰康养老保险股份有限公司");

_citys["保险公司－人身险"].push("幸福人寿保险股份有限公司");

_citys["保险公司－人身险"].push("阳光人寿保险股份有限公司");

_citys["保险公司－人身险"].push("上海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("东吴人寿保险股份有限公司");

_citys["保险公司－人身险"].push("弘康人寿保险股份有限公司");

_citys["保险公司－人身险"].push("吉祥人寿保险股份有限公司");

_citys["保险公司－人身险"].push("复星保德信人寿保险有限公司");

_citys["保险公司－人身险"].push("中韩人寿保险有限公司");

_citys["保险公司－人身险"].push("德华安顾人寿保险有限公司");

_citys["保险公司－人身险"].push("安邦养老保险股份有限公司");

_citys["保险公司－人身险"].push("太保安联健康保险股份有限公司");

_citys["保险公司－人身险"].push("渤海人寿保险股份有限公司");

_citys["保险公司－人身险"].push("国联人寿保险股份有限公司");

_citys["保险公司－财产险"] = [];

_citys["保险公司－财产险"].push("中国人民财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国大地财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国出口信用保险公司");

_citys["保险公司－财产险"].push("中华联合财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国太平洋财产保险股份有限公司");

_citys["保险公司－财产险"].push("中国平安财产保险股份有限公司");

_citys["保险公司－财产险"].push("天安财产保险股份有限公司");

_citys["保险公司－财产险"].push("史带财产保险股份有限公司");

_citys["保险公司－财产险"].push("华安财产保险股份有限公司");

_citys["保险公司－财产险"].push("永安财产保险股份有限公司");

_citys["保险公司－财产险"].push("安联财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("日本财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("利宝保险有限公司");

_citys["保险公司－财产险"].push("安信农业保险股份有限公司");

_citys["保险公司－财产险"].push("中航安盟财产保险有限公司");

_citys["保险公司－财产险"].push("永诚财产保险股份有限公司");

_citys["保险公司－财产险"].push("安华农业保险股份有限公司");

_citys["保险公司－财产险"].push("安盛天平财产保险股份有限公司");

_citys["保险公司－财产险"].push("阳光财产保险股份有限公司");

_citys["保险公司－财产险"].push("阳光农业相互保险公司");

_citys["保险公司－财产险"].push("爱和谊日生同和财产保险（中国）");

_citys["保险公司－财产险"].push("国元农业保险股份有限公司");

_citys["保险公司－财产险"].push("鼎和财产保险股份有限公司");

_citys["保险公司－财产险"].push("中煤财产保险股份有限公司");

_citys["保险公司－财产险"].push("国泰财产保险有限责任公司");

_citys["保险公司－财产险"].push("英大泰和财产保险股份有限公司");

_citys["保险公司－财产险"].push("紫金财产保险股份有限公司");

_citys["保险公司－财产险"].push("日本兴亚财产保险（中国）有限责任公司");

_citys["保险公司－财产险"].push("浙商财产保险股份有限公司");

_citys["保险公司－财产险"].push("信达财产保险股份有限公司");

_citys["保险公司－财产险"].push("富德财产保险股份有限公司");

_citys["保险公司－财产险"].push("鑫安汽车保险股份有限公司");

_citys["保险公司－财产险"].push("北部湾财产保险股份有限公司");

_citys["保险公司－财产险"].push("众安在线财产保险股份有限公司");

_citys["保险公司－财产险"].push("华海财产保险股份有限公司");

_citys["保险公司－财产险"].push("燕赵财产保险股份有限公司");

_citys["保险公司－财产险"].push("太平财产保险有限公司");

_citys["保险公司－财产险"].push("民安财产保险有限公司");

_citys["保险公司－财产险"].push("美亚财产保险有限公司");

_citys["保险公司－财产险"].push("东京海上日动火灾保险（中国）有限公司");

_citys["保险公司－财产险"].push("安盛保险有限公司");

_citys["保险公司－财产险"].push("瑞再企商保险有限公司");

_citys["保险公司－财产险"].push("丘博保险（中国）有限公司");

_citys["保险公司－财产险"].push("三井住友海上火灾保险（中国）有限公司");

_citys["保险公司－财产险"].push("三星财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("中银保险有限公司");

_citys["保险公司－财产险"].push("都邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("渤海财产保险股份有限公司");

_citys["保险公司－财产险"].push("华农财产保险股份有限公司");

_citys["保险公司－财产险"].push("苏黎世财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("中国人寿财产保险股份有限公司");

_citys["保险公司－财产险"].push("安诚财产保险股份有限公司");

_citys["保险公司－财产险"].push("现代财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("长安责任保险股份有限公司");

_citys["保险公司－财产险"].push("劳合社保险（中国）有限公司");

_citys["保险公司－财产险"].push("中意财产保险有限公司");

_citys["保险公司－财产险"].push("有限公司乐爱金财产保险（中国）有限公司");

_citys["保险公司－财产险"].push("富邦财产保险有限公司");

_citys["保险公司－财产险"].push("信利保险（中国）有限公司");

_citys["保险公司－财产险"].push("泰山财产保险股份有限公司");

_citys["保险公司－财产险"].push("锦泰财产保险股份有限公司");

_citys["保险公司－财产险"].push("众诚汽车保险股份有限公司");

_citys["保险公司－财产险"].push("华泰财产保险有限公司");

_citys["保险公司－财产险"].push("长江财产保险股份有限公司");

_citys["保险公司－财产险"].push("诚泰财产保险股份有限公司");

_citys["保险公司－财产险"].push("安邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("恒邦财产保险股份有限公司");

_citys["保险公司－财产险"].push("合众财产保险股份有限公司");

_citys["保险公司－财产险"].push("中路财产保险股份有限公司");

_citys["保险公司－财产险"].push("中原农业保险股份有限公司");

_citys["保险公司－财产险"].push("中国铁路财产保险自保有限公司");

_citys["再保险公司"] = [];

_citys["再保险公司"].push("中国财产再保险有限责任公司");

_citys["再保险公司"].push("中国人寿再保险有限责任公司");

_citys["再保险公司"].push("瑞士再保险股份有限公司北京分公司");

_citys["再保险公司"].push("慕尼黑再保险公司北京分公司");

_citys["再保险公司"].push("德国通用再保险股份公司上海分公司");

_citys["再保险公司"].push("法国再保险公司北京分公司");

_citys["再保险公司"].push("汉诺威再保险股份公司上海分公司");

_citys["再保险公司"].push("太平再保险有限公司");

_citys["再保险公司"].push("RGA美国再保险公司上海分公司");

_citys["保险资产管理公司"] = [];

_citys["保险资产管理公司"].push("中国人保资产管理股份有限公司");

_citys["保险资产管理公司"].push("中国人寿资产管理有限公司");

_citys["保险资产管理公司"].push("华泰资产管理有限公司");

_citys["保险资产管理公司"].push("平安资产管理有限责任公司");

_citys["保险资产管理公司"].push("中再资产管理股份有限公司");

_citys["保险资产管理公司"].push("泰康资产管理有限责任公司");

_citys["保险资产管理公司"].push("太平洋资产管理有限责任公司");

_citys["保险资产管理公司"].push("太平资产管理有限公司");

_citys["保险资产管理公司"].push("新华资产管理股份有限公司");

_citys["保险资产管理公司"].push("安邦资产管理有限责任公司");

_citys["保险资产管理公司"].push("华夏久盈资产管理有限责任公司	");

_citys["保险资产管理公司"].push("生命保险资产管理有限公司");

_citys["保险资产管理公司"].push("光大永明资产管理股份有限公司");

_citys["保险资产管理公司"].push("合众资产管理股份有限公司");

_citys["保险资产管理公司"].push("民生通惠资产管理有限公司");

_citys["保险资产管理公司"].push("阳光资产管理股份有限公司");

_citys["保险资产管理公司"].push("中英益利资产管理股份有限公司");

_citys["保险资产管理公司"].push("中意资产管理有限责任公司");

_citys["保险资产管理公司"].push("华安财保资产管理有限责任公司");

_citys["保险资产管理公司"].push("长城财富资产管理股份有限公司");

_citys["保险资产管理公司"].push("英大保险资产管理有限公司");

_QUESTION = [
  {
    id: 1,
    question: "为贯彻《国务院办公厅关于加强金融消费者权益保护工作的指导意见》，开展保险消费者权益保护教育，具体活动安排如下：",
    answers: ["A", "B", "C", "D"],
    banner: "http://m.giccoo.com/qa/img/banner.jpg",
    link: "http://www.baidu.com"
  }, {
    id: 2,
    question: "为贯彻《国务院办公厅关于加强金融消费者权益保护工作的指导意见》，开展保险消费者权益保护教育，具体活动安排如下：",
    answers: ["a", "b", "c", "d"],
    banner: "http://m.giccoo.com/qa/img/banner.jpg",
    link: "http://www.baidu.com"
  }
];

company = null;

loadStart = function() {
  var count, ep, now;
  count = $("[data-src]").length;
  now = 0;
  ep = $("#loading-text");
  return $("[data-src]").each(function() {
    var img;
    img = new Image();
    img.onload = function() {
      now++;
      ep.text(parseInt(now / count * 100));
      if (now >= count) {
        return loadEnd();
      }
    };
    img.src = $(this).attr("data-src");
    $(this).after(img);
    return $(this).remove();
  });
};

loadEnd = function() {
  riot.mount("#select-company", "select-company");
  riot.mount("#qa", "qa");
  $(".loading").addClass("fadeOut animated");
  return setTimeout(function() {
    return $(".loading").remove();
  }, 520);
};

window.onload = function() {
  var MK, project;
  if (typeof project === "undefined" || project === null) {
    project = "qa";
  }
  if (openid === "") {
    window.location.href = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxb3dd8b8d67e940c4&redirect_uri={url}&response_type=code&scope=snsapi_base&state=123#wechat_redirect".replace("{url}", encodeURIComponent("http://i.giccoo.com/" + project + "/"));
    return false;
  }
  riot.mount("#pages", "pages");
  MK = $("body").width() / $("body").height();
  if ($("body").height() <= 460 || MK > 0.65) {
    $("body").addClass("iphone4");
  }
  $(".btn-join").click(function() {
    $(".page.info-page").removeClass("on");
    return $(".page.note-page").addClass("on");
  });
  $(".btn-company").click(function() {
    if (subscribe === 0) {
      return showFocus();
    }
    return $(".pop.select-company").addClass("on");
  });
  $(".btn-personal").click(function() {
    if (subscribe === 0) {
      return showFocus();
    }
    $(".page.note-page").removeClass("on");
    return $(".page.question-page").addClass("on");
  });
  loadWechatConfig();
  return wx.ready(function() {
    var shareContent;
    shareContent = {
      title: SHARETITLE,
      desc: SHAREDESC,
      link: SHARELINK,
      imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
      success: function() {},
      cancel: function() {}
    };
    wx.onMenuShareTimeline(shareContent);
    wx.onMenuShareAppMessage(shareContent);
    wx.onMenuShareQQ(shareContent);
    return wx.onMenuShareWeibo(shareContent);
  });
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/config?url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};

UpdateShare = function(text) {
  var TimelineShareContent;
  TimelineShareContent = {
    title: text,
    desc: SHAREDESC,
    link: SHARELINK,
    imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
    success: function() {},
    cancel: function() {}
  };
  wx.onMenuShareTimeline(TimelineShareContent);
  wx.onMenuShareAppMessage(TimelineShareContent);
  wx.onMenuShareQQ(TimelineShareContent);
  return wx.onMenuShareWeibo(TimelineShareContent);
};

showFocus = function() {
  return $(".pop.focus-page").addClass("on");
};

hideFocus = function() {
  return $(".pop.focus-page").removeClass("on");
};

CompanyPage = function(name) {
  company = name;
  $(".page.note-page").removeClass("on");
  return $(".page.question-page").addClass("on");
};

POST = function(answers, callback) {
  var data;
  data = {
    openid: openid,
    answer: answers.join(",")
  };
  if (company != null) {
    data.company = company;
  }
  return $.post(POSTurl, data, function(msg) {
    if (msg.recode === 200) {
      SendNote("提交成功");
      return setTimeout(function() {
        return Done(msg);
      }, 3000);
    } else {
      return SendNote(msg.reason);
    }
  });
};

Done = function(msg) {
  var fen;
  fen = msg.info.fen;
  if (msg.info.fen > 20) {
    fen = fen - 10 + parseInt(Math.random() * 10);
  } else {
    fen = fen;
  }
  UpdateShare("恭喜你!保险知识竞赛正确率超过了 " + fen + "% 的网友.");
  $(".page.finished-page #nums").text(fen);
  $(".page").removeClass("on");
  return $(".page.finished-page").addClass("on");
};

showShare = function() {
  return $(".share-box").addClass("on");
};

hideShare = function() {
  return $(".share-box").removeClass("on");
};

SendNote = function(msg, time) {
  if (time == null) {
    time = 3000;
  }
  $("body").append("<note title='" + msg + ("' time='" + time + "'></note>"));
  return riot.mount("note");
};
