// Generated by CoffeeScript 1.10.0
var CompanyPage, Done, POST, SendNote, UpdateShare, _POSTING, _jplink, company, hideFocus, hideShare, loadEnd, loadStart, loadWechatConfig, showFocus, showShare;

Array.prototype.clean = function(deleteValue) {
  var i;
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

company = null;

_jplink = "http://m.baolian365.com/index.php?g=Wap&m=Zixun&a=h5";

loadStart = function() {
  var count, ep, now;
  count = $("[data-src]").length;
  now = 0;
  ep = $("#loading-text");
  return $("[data-src]").each(function() {
    var img;
    img = new Image();
    img.onload = function() {
      now++;
      ep.text(parseInt(now / count * 100));
      if (now >= count) {
        return loadEnd();
      }
    };
    img.src = $(this).attr("data-src");
    $(this).after(img);
    return $(this).remove();
  });
};

loadEnd = function() {
  riot.mount("#select-company", "select-company");
  riot.mount("#qa", "qa");
  $(".loading").addClass("fadeOut animated");
  return setTimeout(function() {
    return $(".loading").remove();
  }, 520);
};

window.onload = function() {
  var MK;
  riot.mount("*");
  MK = $("body").width() / $("body").height();
  if ($("body").height() <= 460 || MK > 0.65) {
    $("body").addClass("iphone4");
  }
  loadWechatConfig();
  return wx.ready(function() {
    var shareContent;
    shareContent = {
      title: SHARETITLE,
      desc: SHAREDESC,
      link: SHARELINK,
      imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
      success: function() {},
      cancel: function() {}
    };
    wx.onMenuShareTimeline(shareContent);
    wx.onMenuShareAppMessage(shareContent);
    wx.onMenuShareQQ(shareContent);
    return wx.onMenuShareWeibo(shareContent);
  });
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/config?url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};

UpdateShare = function(text) {
  var TimelineShareContent;
  TimelineShareContent = {
    title: text,
    desc: SHAREDESC,
    link: SHARELINK,
    imgUrl: "http://disk.giccoo.com/projects/qa/img/share.jpg",
    success: function() {},
    cancel: function() {}
  };
  wx.onMenuShareTimeline(TimelineShareContent);
  wx.onMenuShareAppMessage(TimelineShareContent);
  wx.onMenuShareQQ(TimelineShareContent);
  return wx.onMenuShareWeibo(TimelineShareContent);
};

showFocus = function() {
  return $(".pop.focus-page").addClass("on");
};

hideFocus = function() {
  return $(".pop.focus-page").removeClass("on");
};

CompanyPage = function(name) {
  company = name;
  if (typeof _QA !== "undefined" && _QA !== null) {
    _QA.changeCompany();
  }
  $(".pop.select-company").removeClass("on");
  $(".page.note-page").removeClass("on");
  return $(".page.question-page").addClass("on");
};

_POSTING = false;

POST = function(answers, callback) {
  var data;
  if (_POSTING) {
    return SendNote("正在提交请稍后...");
  }
  _POSTING = true;
  data = {
    openid: openid,
    answer: answers.join(",")
  };
  if (company != null) {
    data.company = company;
  }
  $(".pop.select-company").removeClass("on");
  return $.post(POSTurl, data, function(msg) {
    _POSTING = false;
    if (msg.recode === 200) {
      SendNote("提交成功");
      return setTimeout(function() {
        return Done(msg);
      }, 3000);
    } else if (msg.recode === 202) {
      SendNote("您已经提交过答案,无法变更,即将显示您本次答题的正确率。", 4000);
      return setTimeout(function() {
        return Done(msg, true);
      }, 4000);
    } else if (msg.recode === 203) {
      SendNote("活动已经结束，如果您还没有参与过活动，现在已经无法参与，即将显示您本次答题的正确率。", 4000);
      return setTimeout(function() {
        return Done(msg, true);
      }, 4000);
    } else {
      return SendNote(msg.reason);
    }
  });
};

Done = function(msg, secondTime) {
  var fen;
  if (secondTime == null) {
    secondTime = false;
  }
  $(".pop.select-company").removeClass("on");
  fen = msg.info.fen;
  if (msg.info.fen > 20) {
    fen = fen + parseInt(Math.random() * 9);
  } else {
    fen = fen;
  }
  if (fen > 99) {
    fen = 99;
  }
  UpdateShare("恭喜你!保险知识有奖竞赛正确率超过了 " + fen + "% 的网友.");
  $(".page.finished-page #nums").text(fen);
  $(".page").removeClass("on");
  return $(".page.finished-page").addClass("on");
};

showShare = function() {
  return $(".share-box").addClass("on");
};

hideShare = function() {
  return $(".share-box").removeClass("on");
};

SendNote = function(msg, time) {
  if (time == null) {
    time = 3000;
  }
  $("body").append("<note title='" + msg + ("' time='" + time + "'></note>"));
  return riot.mount("note");
};
