// Generated by CoffeeScript 1.8.0
var ANIMATION_END_NAME, ANIMATION_END_NAMES, BindShare, LoadFinished, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, app, beginload, css3Prefix, fShare, handleFileLoad, hosts, i, loadList, mTestElement, my, preload, refreshShare, reloadWechat, shareFriend, shareTimeline, _Progress, _finishedlist, _i, _len, _wechat, _wechat_bool, _wechat_f;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (_i = 0, _len = VENDORS.length; _i < _len; _i++) {
  i = VENDORS[_i];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

my = {};

my.getid = function(id) {
  return document.getElementById(id);
};

my.getclass = function(cls) {
  return document.getElementsByClassName(cls);
};

my.getbyname = function(name) {
  return document.getElementsByName(name);
};

my.createObjectURL = function(file) {
  if (window.navigator.userAgent.indexOf("Chrome") >= 1 || window.navigator.userAgent.indexOf("Safari") >= 1) {
    return window.webkitURL.createObjectURL(file);
  } else {
    return window.URL.createObjectURL(file);
  }
};

_wechat_f = {
  "appid": "",
  "img_url": "",
  "img_width": 200,
  "img_height": 200,
  "link": "",
  "desc": "",
  "title": ""
};

_wechat = {
  "appid": "",
  "img_url": "",
  "img_width": 200,
  "img_height": 200,
  "link": "",
  "desc": "",
  "title": ""
};

_wechat_bool = false;

reloadWechat = function() {
  shareFriend();
  return shareTimeline();
};

shareFriend = function() {
  if (window.WeixinJSBridge) {
    WeixinJSBridge.invoke('sendAppMessage', _wechat_f);
  }
  return document.title = _wechat_f.title;
};

shareTimeline = function() {
  if (window.WeixinJSBridge) {
    WeixinJSBridge.invoke('shareTimeline', _wechat);
  }
  return document.title = _wechat.title;
};

document.addEventListener('WeixinJSBridgeReady', function() {
  _wechat_bool = true;
  WeixinJSBridge.on('menu:share:appmessage', function(argv) {
    return shareFriend();
  });
  return WeixinJSBridge.on('menu:share:timeline', function(argv) {
    return shareTimeline();
  });
});

BindShare = function(content, url, pic) {
  var list;
  if (url == null) {
    url = window.location.href;
  }
  list = {
    "qweibo": "http://v.t.qq.com/share/share.php?title={title}&url={url}&pic={pic}",
    "renren": "http://share.renren.com/share/buttonshare.do?title={title}&link={url}&pic={pic}",
    "weibo": "http://v.t.sina.com.cn/share/share.php?title={title}&url={url}&pic={pic}",
    "qzone": "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url={url}&title={title}&pic={pic}",
    "facebook": "http://www.facebook.com/sharer/sharer.php?s=100&p[url]={url}}&p[title]={title}&p[summary]={title}&pic={pic}",
    "twitter": "https://twitter.com/intent/tweet?text={title}&pic={pic}",
    "kaixin": "http://www.kaixin001.com/rest/records.php?content={title}&url={url}&pic={pic}",
    "douban": "http://www.douban.com/share/service?bm=&image={pic}&href={url}&updated=&name={title}"
  };
  return $("a[data-share]").each(function(e) {
    return $(this).attr("href", fShare(list[$(this).data('share')], content, url, pic));
  });
};

fShare = function(url, content, sendUrl, pic) {
  var backUrl, shareContent;
  if (pic == null) {
    pic = "";
  }
  content = content;
  shareContent = encodeURIComponent(content);
  pic = encodeURIComponent(pic);
  url = url.replace("{title}", shareContent);
  url = url.replace("{pic}", pic);
  backUrl = encodeURIComponent(sendUrl);
  url = url.replace("{url}", backUrl);
  return url;
};

preload = null;

loadList = [
  {
    id: "logo",
    src: "../libs/img/loading.png"
  }
];

beginload = function($scope, callback) {
  var handleComplete;
  if (preload != null) {
    return "";
  }
  handleComplete = function() {
    return LoadFinished("img", $scope, callback);
  };
  preload = new createjs.LoadQueue();
  preload.on('fileload', handleFileLoad, this);
  preload.on('complete', handleComplete, this);
  return preload.loadManifest(loadList);
};

_Progress = 0;

handleFileLoad = function() {
  var Percentage;
  _Progress++;
  Percentage = Math.ceil((_Progress / loadList.length) * 100);
  return console.log("Load:", Percentage);
};

_finishedlist = [
  {
    name: "img",
    load: false
  }, {
    name: "angular",
    load: false
  }
];

LoadFinished = function(name, $scope, callback) {
  var a, gotoNext, _j, _k, _len1, _len2;
  for (_j = 0, _len1 = _finishedlist.length; _j < _len1; _j++) {
    a = _finishedlist[_j];
    if (a.name === name) {
      a.load = true;
    }
  }
  gotoNext = true;
  for (_k = 0, _len2 = _finishedlist.length; _k < _len2; _k++) {
    a = _finishedlist[_k];
    if (a.load === false) {
      gotoNext = false;
      break;
    }
  }
  if (gotoNext) {
    $scope.loaded = true;
    if (name !== "angular") {
      return $scope.$apply(function() {
        if (typeof callback === "function") {
          return callback.call();
        }
      });
    }
  }
};

loadList = [
  {
    id: "logo",
    src: "../libs/img/loading.png"
  }
];

_wechat_f = {
  "appid": "wxf7ed397bd943c472",
  "img_url": "http://m.giccoo.com/iwatch/img/share.jpg",
  "img_width": 300,
  "img_height": 300,
  "link": "http://m.giccoo.com/shrimp",
  "desc": "这道菜的关键是选择阿根廷红虾.",
  "title": "我刚做了一道'红焖大虾'快来尝尝."
};

_wechat = {
  "appid": "wxf7ed397bd943c472",
  "img_url": "http://m.giccoo.com/iwatch/img/share.jpg",
  "img_width": 300,
  "img_height": 300,
  "link": "http://m.giccoo.com/shrimp",
  "desc": "这道菜的关键是选择阿根廷红虾.",
  "title": "我刚做了一道'红焖大虾'快来尝尝."
};

hosts = "http://g.giccoo.com";

refreshShare = function(title, desc) {
  _wechat_f.title = title;
  _wechat.title = title;
  _wechat_f.desc = desc;
  _wechat.desc = desc;
  return reloadWechat();
};

app = angular.module('kelvin', ["ngRoute", "ngTouch", "ngAnimate"]).config([
  "$routeProvider", "$locationProvider", function($routeProvider, $locationProvider) {
    $routeProvider.when('/', {
      templateUrl: "home.html",
      controller: "MainController",
      controllerAs: "main"
    });
    $routeProvider.when('/create', {
      templateUrl: "create.html",
      controller: "CreateController",
      controllerAs: "create"
    });
    return $routeProvider.when('/share', {
      templateUrl: "share.html",
      controller: "ShareController",
      controllerAs: "share"
    });
  }
]);

app.controller('MainController', function($rootScope, $scope) {
  beginload($scope);
  $rootScope.$on("$routeChangeSuccess", function() {
    return LoadFinished("angular", $scope);
  });
  return $scope.$watch("loaded", function() {
    if ($scope.loaded) {
      return $(".loaded").removeClass("loaded");
    }
  });
});

app.controller("CreateController", function($rootScope, $scope, $animate, $timeout, $location) {});

app.controller("ShareController", function($rootScope, $scope) {});
