// Generated by CoffeeScript 1.8.0
var init, openDoor, _opend;

_opend = false;

init = function() {
  var parallax;
  return parallax = $('.pages').parallax({
    irection: 'vertical',
    drag: false,
    loading: true,
    indicator: false,
    arrow: false,
    onchange: function(index, element, direction) {
      $(".loading").hide();
      if ($(".page").height() < 450) {
        return $("body").addClass("iphone4");
      } else {
        return $("body").removeClass("iphone4");
      }
    }
  });
};

openDoor = function() {
  $(".door").addClass("open");
  if (!_opend) {
    $("#door")[0].play();
  }
  _opend = true;
  return setTimeout(function() {
    return $("[cantmove=true]").attr("cantmove", "false");
  }, 1000);
};

$(document).ready(function() {
  init();
  $(".loading").hide();
  $(".door").on("touchstart", function() {
    return openDoor();
  });
  return setTimeout(function() {
    return openDoor();
  }, 4000);
});
