// Generated by CoffeeScript 1.12.4
var ANIMATION_END_NAME, ANIMATION_END_NAMES, EndLastFrame, FormHeight, FrameFun, Loader, SendNote, Stars, Store, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, _loader, _startDate, _stepList, cdn, changeMain, css3Prefix, debug, global, hideSelf, i, isMM, j, layzr, len, link, loadWechatConfig, loadedEnd, mTestElement, mainSlider, oldslideNumber, passFun, pc, playerDraw, qrcode, secondSlider, tabId, tabId2, taskData, tm, uid;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

(function() {
  var lastTime, vendors, x;
  lastTime = 0;
  vendors = ["webkit", "moz"];
  x = 0;
  while (x > vendors.length && !window.requestAnimationFrame) {
    console.log("" + vendors[x]);
  }
  window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
  window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
  ++x;
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var currTime, id, timeToCall;
      currTime = new Date().getTime();
      timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
      id = window.setTimeout(function() {
        callback(currTime + timeToCall);
      }, timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };
  }
  if (!window.cancelAnimationFrame) {
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
  }
})();

qrcode = function() {
  return (function() {
    var hm, s;
    hm = document.createElement('script');
    hm.onload = function() {
      return new QRCode(document.getElementById("qrcode"), {
        width: 400,
        height: 400,
        text: window.location.href
      });
    };
    hm.src = '/libs/js/min/qrcode.min.js';
    s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(hm, s);
  })();
};

Store = {};

layzr = null;

tm = null;

oldslideNumber = 0;

debug = false;

cdn = "";

isMM = false;

FormHeight = 0;

global = {};

link = "http://api.giccoo.com";

mainSlider = {};

secondSlider = {};

tabId = 0;

tabId2 = 0;

_stepList = ["40,000", "70,000", "120,000"];

debug = false;

if (debug) {
  uid = "30102250";
  pc = "ad6ca3d5d8db6eb4af38dbeb13527470012669a8";
  localStorage.clear();
}

_startDate = new Date();

_startDate.setMonth(7);

_startDate.setDate(13);

_startDate.setHours(0);

_startDate.setMinutes(0);

_startDate.setSeconds(0);

_startDate.setMilliseconds(0);

taskData = [
  {
    startDate: _startDate,
    endDate: new Date(_startDate.getTime() + 10 * 24 * 60 * 60 * 1000)
  }
];

window.onload = function() {
  var MK;
  MK = $("body").width() / $("body").height();
  if ($("body").height() <= 460 || MK > 0.65) {
    $("body").addClass("iphone4");
  }
  $(".loading .content").addClass("on");
  setTimeout(function() {
    return loadedEnd();
  }, 2400);
  $("img[first-load-src]").each(function() {
    return $(this).attr("src", $(this).attr("first-load-src"));
  });
  document.querySelector('body').addEventListener("touchmove", function(e) {
    return e.preventDefault();
  });
  $(".page-one .btn").on("click", function() {
    $(".pages .page-one")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-one").addClass("fadeOut animated");
    $(".pages .page-two")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-two").addClass("on");
    setTimeout(function() {
      return $(".pages .page-one").removeClass("on fadeOut animated");
    }, 500);
    return $("img[second-load-src]").each(function() {
      return $(this).attr("src", $(this).attr("second-load-src"));
    });
  });
  $(".page-four .btn-1").on("click", function() {
    $(".pages .page-four")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-four").addClass("fadeOut animated");
    $(".pages .page-four-1")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-four-1").addClass("on");
    Stars(".page-four-3 .stars", 20);
    setTimeout(function() {
      return $(".pages .page-four").removeClass("on fadeOut animated");
    }, 550);
    return $("img[last-load-src]").each(function() {
      return $(this).attr("src", $(this).attr("last-load-src"));
    });
  });
  $(".page-four .btn-2").on("click", function() {
    $(".pages .page-four")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-four").addClass("fadeOut animated");
    $(".pages .page-four-3")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-four-3").addClass("on");
    Stars(".page-four-3 .stars", 20);
    setTimeout(function() {
      return $(".pages .page-four").removeClass("on fadeOut animated");
    }, 550);
    return $("img[last-load-src]").each(function() {
      return $(this).attr("src", $(this).attr("last-load-src"));
    });
  });
  $(".page-five .btn-1").on("click", function() {
    $(".pages .page-five")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-five").addClass("fadeOut animated");
    $(".pages .page-five-1")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-five-1").addClass("on");
    Stars(".page-five-3 .stars", 20);
    return setTimeout(function() {
      return $(".pages .page-five").removeClass("on fadeOut animated");
    }, 550);
  });
  $(".page-five .btn-2").on("click", function() {
    $(".pages .page-five")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-five").addClass("fadeOut animated");
    $(".pages .page-five-3")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-five-3").addClass("on");
    Stars(".page-five-3 .stars", 20);
    return setTimeout(function() {
      return $(".pages .page-five").removeClass("on fadeOut animated");
    }, 550);
  });
  $(".page-six .btn-1").on("click", function() {
    $(".pages .page-six")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-six").addClass("fadeOut animated");
    $(".pages .page-seven")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-seven").addClass("on");
    Stars(".page-seven .stars-1", 15);
    Stars(".page-seven .stars-2", 15);
    Stars(".page-seven .stars-3", 15);
    return setTimeout(function() {
      return $(".pages .page-six").removeClass("on fadeOut animated");
    }, 550);
  });
  $(".page-seven .bg").on("click", function() {
    $("#video")[0].play();
    $(".pages .page-seven")[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
    $(".pages .page-seven")[0].addEventListener(ANIMATION_END_NAME, hideSelf);
    $(".pages .page-seven").addClass("fadeOut animated");
    $(".pages .page-eight")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
    return $(".pages .page-eight").addClass("on");
  });
  loadWechatConfig();
  wx.ready(function() {
    var shareContent;
    shareContent = {
      title: "潮汐更迭 共续蔚蓝心动",
      desc: "LA MER海蓝之谜邀您一起参与世界海洋日艺术展",
      link: "http://m.giccoo.com/lamer/",
      imgUrl: "http://image.giccoo.com/projects/lamer/img/share.jpg",
      success: function() {},
      cancel: function() {}
    };
    wx.onMenuShareTimeline(shareContent);
    wx.onMenuShareAppMessage(shareContent);
    wx.onMenuShareQQ(shareContent);
    return wx.onMenuShareWeibo(shareContent);
  });
  return true;
};

playerDraw = function() {
  var c, canvas, h, v, w;
  v = document.getElementById('video');
  canvas = document.getElementById('player');
  c = canvas.getContext('2d');
  w = 620;
  h = 360;
  c.drawImage(v, 0, 0, w, h);
  return requestAnimationFrame(playerDraw);
};

loadWechatConfig = function() {
  var hm, s, url;
  url = encodeURIComponent(window.location.href.split("#")[0]);
  url = url.replace('&', '%26');
  hm = document.createElement('script');
  hm.src = "http://api.giccoo.com/api/config?debug=true&url=" + url;
  s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(hm, s);
};

EndLastFrame = function(evt) {
  if ($(evt.target).is(".text")) {
    return setTimeout(function() {
      return $(".page-last").addClass("on");
    }, 1700);
  }
};

loadedEnd = function() {
  $(".loading").addClass("fadeOut animated duration-5");
  $(".pages .page-one").addClass("on");
  $(".pages .page-one")[0].addEventListener(ANIMATION_END_NAME, FrameFun);
  Stars(".page-one .stars-1", 20);
  Stars(".page-one .stars-2", 20);
  Stars(".page-one .stars-3", 20);
  return setTimeout(function() {
    return $(".loading").remove();
  }, 550);
};

FrameFun = function(evt) {
  var parent, wait;
  if ($(evt.target).is(".last")) {
    parent = $(evt.target).parents(".page");
    wait = parseInt(parent.attr("wait"));
    return setTimeout(function() {
      return passFun(evt);
    }, wait);
  }
};

passFun = function(evt) {
  var parent;
  parent = $(evt.target).parents(".page");
  parent[0].removeEventListener(ANIMATION_END_NAME, FrameFun);
  parent[0].addEventListener(ANIMATION_END_NAME, hideSelf);
  if (parent.attr("next")) {
    console.log("next page");
    parent.addClass("fadeOut animated");
    $(parent.attr("next")).addClass("on");
    return $(parent.attr("next"))[0].addEventListener(ANIMATION_END_NAME, FrameFun);
  } else {
    return console.log("stop this");
  }
};

hideSelf = function(evt) {
  $(evt.target).removeClass("on fadeOut animated");
  return $(evt.target)[0].removeEventListener(ANIMATION_END_NAME, hideSelf);
};

changeMain = function() {};

SendNote = function(msg, time) {
  if (time == null) {
    time = 3000;
  }
  $("body").append("<note title='" + msg + ("' time='" + time + "'></note>"));
  return riot.mount("note");
};

_loader = {};

Loader = function(id, title, type, time, more) {
  if (title == null) {
    title = "";
  }
  if (type == null) {
    type = "ball";
  }
  if (time == null) {
    time = 0;
  }
  if (more == null) {
    more = "";
  }
  if ($("#" + id).length > 0) {
    return _loader[id].loadend();
  }
  $("body").append("<loader id='" + id + "' title='" + title + "' type='" + type + ("' time='" + time + "'>" + more + "</loader>"));
  return riot.mount("loader");
};

Stars = function(target, num) {
  var delay, duration, index, k, randomX, randomY, ref, results, size, star, stars;
  stars = $(target);
  results = [];
  for (index = k = 0, ref = num; 0 <= ref ? k < ref : k > ref; index = 0 <= ref ? ++k : --k) {
    randomX = Math.random() * 100;
    randomY = Math.random() * 100;
    delay = parseInt(Math.random() * 500);
    duration = parseInt(Math.random() * 1500 + 1500);
    size = Math.random() * 2 + 1;
    star = $("<div>");
    star.addClass("star");
    star.css({
      "top": randomX + "%",
      "left": randomY + "%",
      "width": size + "px",
      "height": size + "px",
      "animation-delay": delay + "ms",
      "animation-duration": duration + "ms"
    });
    stars.append(star);
    results.push(console.log(star));
  }
  return results;
};
