// Generated by CoffeeScript 1.9.1
var ANIMATION_END_NAME, ANIMATION_END_NAMES, TRANSITION_END_NAME, TRANSITION_END_NAMES, VENDORS, _citys, changePoint, css3Prefix, i, j, len, mTestElement;

VENDORS = ["Moz", 'webkit', 'ms', 'O'];

TRANSITION_END_NAMES = {
  "Moz": "transitionend",
  "webkit": "webkitTransitionEnd",
  "ms": "MSTransitionEnd",
  "O": "oTransitionEnd"
};

ANIMATION_END_NAMES = {
  "Moz": "animationend",
  "webkit": "webkitAnimationEnd",
  "ms": "MSAnimationEnd",
  "O": "oAnimationEnd"
};

mTestElement = document.createElement("div");

for (j = 0, len = VENDORS.length; j < len; j++) {
  i = VENDORS[j];
  css3Prefix = i;
  if ((css3Prefix + "Transition") in mTestElement.style) {
    break;
  }
  css3Prefix = false;
}

if (css3Prefix) {
  TRANSITION_END_NAME = TRANSITION_END_NAMES[css3Prefix];
  ANIMATION_END_NAME = ANIMATION_END_NAMES[css3Prefix];
}

Array.prototype.clean = function(deleteValue) {
  i = 0;
  while (i < this.length) {
    if (this[i] === deleteValue) {
      this.splice(i, 1);
      i--;
    }
    i++;
  }
  return this;
};

HTMLElement.prototype.getStyle = function(className) {
  if (this.currentStyle) {
    return this.currentStyle(className);
  } else {
    return document.defaultView.getComputedStyle(this, false)[className];
  }
};

(function() {
  var lastTime, vendors, x;
  lastTime = 0;
  vendors = ["webkit", "moz"];
  x = 0;
  while (x > vendors.length && !window.requestAnimationFrame) {
    console.log("" + vendors[x]);
  }
  window.requestAnimationFrame = window[vendors[x] + "RequestAnimationFrame"];
  window.cancelAnimationFrame = window[vendors[x] + "CancelAnimationFrame"] || window[vendors[x] + "CancelRequestAnimationFrame"];
  ++x;
  if (!window.requestAnimationFrame) {
    window.requestAnimationFrame = function(callback, element) {
      var currTime, id, timeToCall;
      currTime = new Date().getTime();
      timeToCall = Math.max(0, 16.7 - (currTime - lastTime));
      id = window.setTimeout(function() {
        callback(currTime + timeToCall);
      }, timeToCall);
      lastTime = currTime + timeToCall;
      return id;
    };
  }
  if (!window.cancelAnimationFrame) {
    window.cancelAnimationFrame = function(id) {
      clearTimeout(id);
    };
  }
})();

_citys = {};

_citys["北京"] = {};

_citys["甘肃"] = {};

_citys["河北"] = {};

_citys["黑龙江"] = {};

_citys["吉林"] = {};

_citys["辽宁"] = {};

_citys["内蒙古"] = {};

_citys["山东"] = {};

_citys["山西"] = {};

_citys["陕西"] = {};

_citys["天津"] = {};

_citys["新疆"] = {};

_citys["安徽"] = {};

_citys["河南"] = {};

_citys["湖北"] = {};

_citys["江苏"] = {};

_citys["江西"] = {};

_citys["上海"] = {};

_citys["浙江"] = {};

_citys["福建"] = {};

_citys["广东"] = {};

_citys["广西"] = {};

_citys["贵州"] = {};

_citys["海南"] = {};

_citys["湖南"] = {};

_citys["四川"] = {};

_citys["云南"] = {};

_citys["重庆"] = {};

_citys["宁夏"] = {};

_citys["青海"] = {};

_citys["北京"]["北京"] = [];

_citys["甘肃"]["兰州"] = [];

_citys["河北"]["石家庄"] = [];

_citys["河北"]["唐山"] = [];

_citys["黑龙江"]["哈尔滨"] = [];

_citys["吉林"]["长春"] = [];

_citys["辽宁"]["大连"] = [];

_citys["辽宁"]["沈阳"] = [];

_citys["内蒙古"]["包头"] = [];

_citys["内蒙古"]["呼和浩特"] = [];

_citys["山东"]["济南"] = [];

_citys["山东"]["青岛"] = [];

_citys["山东"]["烟台"] = [];

_citys["山西"]["太原"] = [];

_citys["陕西"]["西安"] = [];

_citys["天津"]["天津"] = [];

_citys["新疆"]["乌鲁木齐"] = [];

_citys["安徽"]["合肥"] = [];

_citys["河南"]["郑州"] = [];

_citys["湖北"]["武汉"] = [];

_citys["江苏"]["常州"] = [];

_citys["江苏"]["南通"] = [];

_citys["江苏"]["苏州"] = [];

_citys["江苏"]["无锡"] = [];

_citys["江苏"]["扬州"] = [];

_citys["江西"]["南昌"] = [];

_citys["上海"]["上海"] = [];

_citys["浙江"]["杭州"] = [];

_citys["浙江"]["嘉兴"] = [];

_citys["浙江"]["宁波"] = [];

_citys["浙江"]["绍兴"] = [];

_citys["浙江"]["台州"] = [];

_citys["浙江"]["温州"] = [];

_citys["福建"]["泉州"] = [];

_citys["广东"]["东莞"] = [];

_citys["广东"]["佛山"] = [];

_citys["广东"]["广州"] = [];

_citys["广东"]["揭阳"] = [];

_citys["广东"]["汕头"] = [];

_citys["广东"]["深圳"] = [];

_citys["广东"]["中山"] = [];

_citys["广东"]["珠海"] = [];

_citys["广西"]["南宁"] = [];

_citys["贵州"]["贵阳"] = [];

_citys["海南"]["海口"] = [];

_citys["湖南"]["长沙"] = [];

_citys["四川"]["成都"] = [];

_citys["云南"]["昆明"] = [];

_citys["重庆"]["重庆"] = [];

_citys["山东"]["潍坊"] = [];

_citys["河北"]["保定"] = [];

_citys["江苏"]["南京"] = [];

_citys["辽宁"]["鞍山"] = [];

_citys["陕西"]["榆林"] = [];

_citys["山东"]["济宁"] = [];

_citys["山东"]["临沂"] = [];

_citys["山东"]["淄博"] = [];

_citys["山东"]["泰安"] = [];

_citys["山东"]["东营"] = [];

_citys["河北"]["邯郸"] = [];

_citys["四川"]["乐山"] = [];

_citys["黑龙江"]["大庆"] = [];

_citys["宁夏"]["银川"] = [];

_citys["内蒙古"]["赤峰"] = [];

_citys["青海"]["西宁"] = [];

_citys["河南"]["洛阳"] = [];

_citys["山西"]["大同"] = [];

_citys["广西"]["桂林"] = [];

_citys["浙江"]["湖州"] = [];

_citys["江苏"]["徐州"] = [];

_citys["福建"]["厦门"] = [];

_citys["江苏"]["泰州"] = [];

_citys["广西"]["柳州"] = [];

_citys["福建"]["福州"] = [];

_citys["江西"]["赣州"] = [];

_citys["江苏"]["镇江"] = [];

_citys["河南"]["平顶山"] = [];

_citys["辽宁"]["锦州"] = [];

_citys["福建"]["龙岩"] = [];

_citys["河南"]["安阳"] = [];

_citys["山东"]["威海"] = [];

_citys["江苏"]["盐城"] = [];

_citys["安徽"]["阜阳"] = [];

_citys["四川"]["绵阳"] = [];

_citys["福建"]["三明"] = [];

_citys["河南"]["商丘"] = [];

_citys["江西"]["九江"] = [];

_citys["安徽"]["芜湖"] = [];

_citys["山东"]["滨州"] = [];

_citys["江苏"]["常熟"] = [];

_citys["江西"]["上饶"] = [];

_citys["山东"]["德州"] = [];

_citys["河北"]["邢台"] = [];

_citys["云南"]["红河"] = [];

_citys["福建"]["漳州"] = [];

_citys["湖南"]["株洲"] = [];

_citys["四川"]["南充"] = [];

_citys["湖北"]["襄阳"] = [];

_citys["河南"]["南阳"] = [];

_citys["陕西"]["咸阳"] = [];

_citys["福建"]["莆田"] = [];

_citys["吉林"]["吉林"] = [];

_citys["浙江"]["金华"] = [];

_citys["陕西"]["宝鸡"] = [];

_citys["陕西"]["延安"] = [];

_citys["浙江"]["义乌"] = [];

_citys["河南"]["新乡"] = [];

_citys["河北"]["沧州"] = [];

_citys["山西"]["临汾"] = [];

_citys["浙江"]["舟山"] = [];

_citys["山西"]["运城"] = [];

_citys["北京"]["北京"].push({
  code: "BJG",
  name: "北京百旺沃瑞汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJC",
  name: "北京中汽南方华北汽车服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJC",
  name: "北京中汽南方华北汽车服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJE",
  name: "北京中诚海华汽车销售有限责任公司"
});

_citys["北京"]["北京"].push({
  code: "BJF",
  name: "北京宝辰欧雅汽车销售服务有限公司"
});

_citys["甘肃"]["兰州"].push({
  code: "LZA",
  name: "甘肃福康汽车贸易有限公司"
});

_citys["河北"]["石家庄"].push({
  code: "HBC",
  name: "石家庄冀东东沃汽车销售服务有限公司"
});

_citys["河北"]["唐山"].push({
  code: "HBD",
  name: "唐山庞大兴沃汽车销售服务有限公司"
});

_citys["黑龙江"]["哈尔滨"].push({
  code: "HRA",
  name: "黑龙江尊荣富沃汽车贸易有限公司"
});

_citys["吉林"]["长春"].push({
  code: "CCA",
  name: "吉林盛荣汽车贸易有限公司"
});

_citys["辽宁"]["大连"].push({
  code: "DLA",
  name: "尊荣亿方集团有限公司"
});

_citys["辽宁"]["大连"].push({
  code: "DLA",
  name: "尊荣亿方集团有限公司中山路分公司"
});

_citys["辽宁"]["沈阳"].push({
  code: "SYA",
  name: "辽宁尊荣汽车贸易有限公司"
});

_citys["内蒙古"]["包头"].push({
  code: "MGC",
  name: "包头市庞大兴沃汽车销售服务有限责任公司"
});

_citys["内蒙古"]["呼和浩特"].push({
  code: "MGB",
  name: "呼和浩特市庞大兴沃汽车销售服务有限责任公司"
});

_citys["山东"]["济南"].push({
  code: "JND",
  name: "山东富豪汽车销售服务有限公司"
});

_citys["山东"]["青岛"].push({
  code: "QDA",
  name: "青岛富豪汽车销售服务有限公司"
});

_citys["山东"]["烟台"].push({
  code: "YTA",
  name: "烟台富豪汽车销售服务有限公司"
});

_citys["山西"]["太原"].push({
  code: "TYA",
  name: "太原市富豪新华夏汽车连锁销售有限公司"
});

_citys["陕西"]["西安"].push({
  code: "XAA",
  name: "陕西佳豪汽车服务有限公司"
});

_citys["天津"]["天津"].push({
  code: "TJA",
  name: "天津中汽南方汽车销售服务有限公司"
});

_citys["新疆"]["乌鲁木齐"].push({
  code: "XJB",
  name: "新疆金涛汽车贸易有限公司"
});

_citys["安徽"]["合肥"].push({
  code: "HFA",
  name: "合肥捷沃汽车贸易有限责任公司"
});

_citys["河南"]["郑州"].push({
  code: "HNB",
  name: "河南省锦堂盛汽车有限公司"
});

_citys["湖北"]["武汉"].push({
  code: "WHA",
  name: "武汉富豪汽车销售有限公司"
});

_citys["江苏"]["常州"].push({
  code: "CZA",
  name: "常州富豪汽车销售服务有限公司"
});

_citys["江苏"]["南通"].push({
  code: "NTA",
  name: "南通东沃汽车销售服务有限公司"
});

_citys["江苏"]["苏州"].push({
  code: "SUA",
  name: "苏州世之贸汽车贸易有限公司"
});

_citys["江苏"]["苏州"].push({
  code: "SUB",
  name: "通孚祥（苏州）汽车销售服务有限公司"
});

_citys["江苏"]["无锡"].push({
  code: "WXB",
  name: "无锡东方吉羊汽车销售服务有限公司"
});

_citys["江苏"]["扬州"].push({
  code: "YZA",
  name: "扬州富豪汽车销售有限公司"
});

_citys["江西"]["南昌"].push({
  code: "NCA",
  name: "江西绿地名沃汽车销售服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHA",
  name: "上海世之沃汽车销售服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHE",
  name: "上海世之沃汽车销售服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHC",
  name: "上海通孚祥汽车贸易有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHD",
  name: "上海永达东沃汽车销售服务有限公司"
});

_citys["浙江"]["杭州"].push({
  code: "HZA",
  name: "杭州世之贸汽车服务有限公司"
});

_citys["浙江"]["杭州"].push({
  code: "HZC",
  name: "浙江元通元瑞汽车有限公司"
});

_citys["浙江"]["嘉兴"].push({
  code: "JXA",
  name: "嘉兴元通元瑞汽车有限公司"
});

_citys["浙江"]["宁波"].push({
  code: "NBB",
  name: "宁波元通元瑞汽车有限公司"
});

_citys["浙江"]["绍兴"].push({
  code: "SXA",
  name: "绍兴和诚海昌汽车服务有限公司"
});

_citys["浙江"]["台州"].push({
  code: "TZA",
  name: "台州凯和汽车贸易有限公司"
});

_citys["浙江"]["温州"].push({
  code: "WZA",
  name: "温州东昌实业有限公司"
});

_citys["福建"]["泉州"].push({
  code: "QZA",
  name: "泉州市鸿海汽车贸易有限公司"
});

_citys["广东"]["东莞"].push({
  code: "DGA",
  name: "东莞中汽南方汽车销售服务有限公司"
});

_citys["广东"]["佛山"].push({
  code: "NHA",
  name: "佛山市富豪汽车销售服务有限公司"
});

_citys["广东"]["佛山"].push({
  code: "NHA",
  name: "佛山市富豪汽车销售服务有限公司"
});

_citys["广东"]["广州"].push({
  code: "GZB",
  name: "广州市永安富豪汽车贸易有限公司"
});

_citys["广东"]["揭阳"].push({
  code: "JYA",
  name: "揭阳市恒丰汽车贸易有限公司"
});

_citys["广东"]["汕头"].push({
  code: "STA",
  name: "汕头市恒康汽车贸易有限公司"
});

_citys["广东"]["深圳"].push({
  code: "SZA",
  name: "深圳市中汽南方汽车维修有限公司"
});

_citys["广东"]["深圳"].push({
  code: "SZB",
  name: "深圳市中汽南方华沃汽车销售服务有限公司"
});

_citys["广东"]["中山"].push({
  code: "ZSA",
  name: "中山中汽南方汽车销售服务有限公司"
});

_citys["广东"]["珠海"].push({
  code: "ZHA",
  name: "珠海中汽南方汽车销售服务有限公司"
});

_citys["广西"]["南宁"].push({
  code: "NNA",
  name: "广西弘瑞汽车销售服务有限公司"
});

_citys["贵州"]["贵阳"].push({
  code: "GYA",
  name: "贵州天鼎汽车服务有限责任公司"
});

_citys["海南"]["海口"].push({
  code: "HKA",
  name: "海南天昌达汽车销售服务有限公司"
});

_citys["湖南"]["长沙"].push({
  code: "CSA",
  name: "湖南中汽南方汽车销售服务有限公司"
});

_citys["四川"]["成都"].push({
  code: "CDA",
  name: "四川三和汽车服务有限公司"
});

_citys["四川"]["成都"].push({
  code: "CDC",
  name: "四川通孚祥汽车贸易有限公司"
});

_citys["云南"]["昆明"].push({
  code: "KMA",
  name: "云南富豪汽车销售服务有限公司"
});

_citys["重庆"]["重庆"].push({
  code: "CQA",
  name: "重庆西南富豪汽车有限公司"
});

_citys["山东"]["潍坊"].push({
  code: "JNC",
  name: "潍坊诺德汽车服务有限公司"
});

_citys["重庆"]["重庆"].push({
  code: "CQC",
  name: "重庆龙华实业集团沃华汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJK",
  name: "北京海之沃汽车服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHF",
  name: "上海通孚祥汽车销售服务有限公司"
});

_citys["山西"]["太原"].push({
  code: "TYA",
  name: "太原市富豪新华夏汽车连锁销售有限公司"
});

_citys["河北"]["保定"].push({
  code: "HBE",
  name: "保定庞大兴沃汽车销售服务有限公司"
});

_citys["江苏"]["南京"].push({
  code: "NJB",
  name: "江苏世贸泰信东盛汽车贸易有限公司"
});

_citys["辽宁"]["鞍山"].push({
  code: "ASA",
  name: "鞍山尊荣富沃汽车贸易有限公司"
});

_citys["山东"]["济南"].push({
  code: "JNF",
  name: "山东新富豪汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJL",
  name: "北京中汽南方中关汽车销售有限公司"
});

_citys["陕西"]["榆林"].push({
  code: "YLA",
  name: "陕西佳豪金鼎汽车服务有限公司"
});

_citys["云南"]["昆明"].push({
  code: "KMB",
  name: "云南华沃汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJH",
  name: "北京燕豪汽车销售服务有限公司"
});

_citys["广东"]["东莞"].push({
  code: "DGB",
  name: "东莞市世沃汽车销售服务有限公司"
});

_citys["山东"]["济宁"].push({
  code: "JNE",
  name: "济宁恒昌汽车销售有限公司"
});

_citys["山东"]["临沂"].push({
  code: "LYA",
  name: "临沂富豪汽车销售服务有限公司"
});

_citys["广东"]["佛山"].push({
  code: "SDB",
  name: "佛山市顺德区世维汽车销售服务有限公司"
});

_citys["广东"]["广州"].push({
  code: "GZC",
  name: "广州世祥汽车销售有限公司"
});

_citys["江苏"]["无锡"].push({
  code: "WXC",
  name: "无锡富绅汽车销售服务有限公司"
});

_citys["陕西"]["西安"].push({
  code: "XAC",
  name: "陕西佳骏汽车服务有限公司"
});

_citys["山东"]["淄博"].push({
  code: "JNB",
  name: "淄博奥德达汽车服务有限公司"
});

_citys["山东"]["青岛"].push({
  code: "QDB",
  name: "青岛富融汽车销售服务有限公司"
});

_citys["山东"]["泰安"].push({
  code: "TAA",
  name: "泰安富豪汽车销售服务有限公司"
});

_citys["山东"]["东营"].push({
  code: "DYA",
  name: "东营市富豪汽车销售服务有限责任公司"
});

_citys["河北"]["邯郸"].push({
  code: "HBF",
  name: "邯郸市庞大兴沃汽车销售服务有限公司"
});

_citys["四川"]["乐山"].push({
  code: "CDC",
  name: "乐山通孚祥汽车销售服务有限公司"
});

_citys["黑龙江"]["大庆"].push({
  code: "DQA",
  name: "大庆尊荣汽车贸易有限公司"
});

_citys["宁夏"]["银川"].push({
  code: "YCB",
  name: "宁夏佳丰汽车服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHG",
  name: "上海永达嘉沃汽车销售服务有限公司"
});

_citys["浙江"]["杭州"].push({
  code: "HZD",
  name: "浙江万友汽车有限公司"
});

_citys["内蒙古"]["赤峰"].push({
  code: "MGE",
  name: "赤峰市兴沃汽车销售服务有限责任公司"
});

_citys["浙江"]["杭州"].push({
  code: "HZF",
  name: "杭州中沃汽车销售服务有限公司"
});

_citys["辽宁"]["沈阳"].push({
  code: "SYC",
  name: "沈阳尊荣富沃汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJM",
  name: "北京元之沃汽车服务有限公司"
});

_citys["天津"]["天津"].push({
  code: "TJC",
  name: "天津通孚祥汽车销售服务有限公司"
});

_citys["青海"]["西宁"].push({
  code: "QHA",
  name: "青海赛亚金孚汽车销售服务有限公司"
});

_citys["河南"]["洛阳"].push({
  code: "HND",
  name: "洛阳恒信瑞沃汽车销售服务有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJK",
  name: "北京海之沃汽车服务有限公司西三环分公司"
});

_citys["山西"]["大同"].push({
  code: "BJK",
  name: "大同市雁之沃汽车服务有限公司"
});

_citys["广西"]["桂林"].push({
  code: "NNA",
  name: "广西弘瑞汽车销售服务有限公司桂林分公司"
});

_citys["甘肃"]["兰州"].push({
  code: "LZC",
  name: "兰州庞大兴沃汽车销售服务有限公司"
});

_citys["湖北"]["武汉"].push({
  code: "WHC",
  name: "武汉富融汽车销售服务有限公司"
});

_citys["四川"]["成都"].push({
  code: "CDD",
  name: "四川长征超越汽车销售服务有限公司"
});

_citys["河南"]["郑州"].push({
  code: "HNC",
  name: "郑州鼎沃汽车销售服务有限公司"
});

_citys["浙江"]["湖州"].push({
  code: "HZE",
  name: "湖州瑞杰汽车销售服务有限责任公司"
});

_citys["江苏"]["无锡"].push({
  code: "JYB",
  name: "江阴东方沃邦汽车销售服务有限公司"
});

_citys["江苏"]["徐州"].push({
  code: "XZA",
  name: "徐州世贸泰信汽车销售服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHH",
  name: "上海永达申杰汽车销售服务有限公司"
});

_citys["广东"]["广州"].push({
  code: "GZA",
  name: "广东中汽南方汽车销售服务有限公司"
});

_citys["福建"]["厦门"].push({
  code: "XMA",
  name: "厦门新成功瑞沃汽车有限公司"
});

_citys["吉林"]["长春"].push({
  code: "CCB",
  name: "长春市维信汽车销售有限公司"
});

_citys["安徽"]["合肥"].push({
  code: "HFC",
  name: "合肥瑞杰汽车贸易有限责任公司"
});

_citys["江苏"]["泰州"].push({
  code: "TZD",
  name: "泰州富豪汽车销售服务有限公司"
});

_citys["福建"]["厦门"].push({
  code: "XMB",
  name: "厦门中升沃茂汽车销售服务有限公司"
});

_citys["江苏"]["无锡"].push({
  code: "YXA",
  name: "宜兴东方沃邦汽车销售服务有限公司"
});

_citys["广西"]["柳州"].push({
  code: "NNC",
  name: "柳州弘耀汽车销售服务有限公司"
});

_citys["云南"]["昆明"].push({
  code: "KMC",
  name: "昆明庞润荣沃汽车销售服务有限公司"
});

_citys["福建"]["福州"].push({
  code: "FZB",
  name: "福建吉诺富豪汽车贸易有限公司"
});

_citys["福建"]["泉州"].push({
  code: "QZB",
  name: "泉州中升沃茂汽车销售服务有限公司"
});

_citys["黑龙江"]["哈尔滨"].push({
  code: "HRB",
  name: "哈尔滨尊荣亿方汽车贸易有限公司"
});

_citys["江西"]["赣州"].push({
  code: "GAA",
  name: "赣州市绿地祥沃汽车销售服务有限公司"
});

_citys["湖北"]["武汉"].push({
  code: "WHE",
  name: "武汉恒信瑞沃汽车销售服务有限公司"
});

_citys["江苏"]["镇江"].push({
  code: "ZJA",
  name: "镇江世贸泰信汽车销售服务有限公司"
});

_citys["陕西"]["西安"].push({
  code: "XAD",
  name: "西安天润汽车销售服务有限公司"
});

_citys["河南"]["平顶山"].push({
  code: "HNE",
  name: "平顶山市丰海实业有限公司"
});

_citys["辽宁"]["大连"].push({
  code: "DLB",
  name: "大连尊荣汽车销售有限公司"
});

_citys["福建"]["福州"].push({
  code: "FZB",
  name: "福建吉诺富豪汽车贸易有限公司"
});

_citys["辽宁"]["锦州"].push({
  code: "JZA",
  name: "锦州尊荣汽车贸易有限公司"
});

_citys["北京"]["北京"].push({
  code: "BJN",
  name: "北京宝辰沃雅汽车销售服务有限公司"
});

_citys["广东"]["深圳"].push({
  code: "SZC",
  name: "深圳市德顺行汽车销售服务有限公司"
});

_citys["福建"]["龙岩"].push({
  code: "LYB",
  name: "龙岩市英瑞福汽车销售服务有限公司"
});

_citys["湖南"]["长沙"].push({
  code: "CSC",
  name: "长沙建沃汽车销售有限公司"
});

_citys["贵州"]["贵阳"].push({
  code: "GYB",
  name: "贵阳中沃汽车销售服务有限公司"
});

_citys["河南"]["安阳"].push({
  code: "AYA",
  name: "安阳市东安汽车销售服务有限责任公司"
});

_citys["山东"]["威海"].push({
  code: "WHD",
  name: "威海富豪汽车销售服务有限公司"
});

_citys["江苏"]["盐城"].push({
  code: "YCC",
  name: "盐城东昌汽车销售服务有限公司"
});

_citys["安徽"]["阜阳"].push({
  code: "FYA",
  name: "阜阳瑞杰豪骏汽车销售服务有限公司"
});

_citys["四川"]["绵阳"].push({
  code: "MYA",
  name: "绵阳通孚祥汽车销售服务有限公司"
});

_citys["福建"]["三明"].push({
  code: "SMA",
  name: "三明吉诺富豪汽车贸易有限公司"
});

_citys["河南"]["商丘"].push({
  code: "SQA",
  name: "商丘商沃汽车销售服务有限公司"
});

_citys["河北"]["保定"].push({
  code: "BDB",
  name: "保定轩宇骐骥汽车销售服务有限公司"
});

_citys["江西"]["九江"].push({
  code: "JJA",
  name: "九江福沃汽车有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHI",
  name: "上海伟途汽车销售服务有限公司"
});

_citys["江苏"]["苏州"].push({
  code: "SUD",
  name: "苏州东昌新豪汽车销售服务有限公司"
});

_citys["浙江"]["宁波"].push({
  code: "NBA",
  name: "宁波丰颐汽车销售服务有限公司"
});

_citys["上海"]["上海"].push({
  code: "SHA",
  name: "上海世之沃汽车销售服务有限公司"
});

_citys["安徽"]["芜湖"].push({
  code: "HFB",
  name: "芜湖瑞杰豪骏汽车贸易有限责任公司"
});

_citys["河北"]["唐山"].push({
  code: "TSC",
  name: "唐山凯沃商贸有限公司"
});

_citys["山东"]["滨州"].push({
  code: "BZA",
  name: "滨州东泰汽车有限公司"
});

_citys["江苏"]["常熟"].push({
  code: "SUC",
  name: "通孚祥（常熟）汽车销售服务有限公司"
});

_citys["江西"]["南昌"].push({
  code: "NCB",
  name: "江西东沃汽车销售服务有限公司"
});

_citys["江西"]["上饶"].push({
  code: "SRA",
  name: "上饶市名一汽车销售服务有限公司"
});

_citys["内蒙古"]["呼和浩特"].push({
  code: "MGG",
  name: "呼和浩特市宝辰欧雅汽车销售服务有限公司"
});

_citys["山东"]["德州"].push({
  code: "DZA",
  name: "德州瑞沃商贸有限公司"
});

_citys["河北"]["邢台"].push({
  code: "XTA",
  name: "邢台银龙汽车销售服务有限公司"
});

_citys["云南"]["红河"].push({
  code: "HHA",
  name: "红河沃捷汽车销售服务有限公司"
});

_citys["福建"]["漳州"].push({
  code: "ZZC",
  name: "漳州新成功汽车贸易有限公司"
});

_citys["湖南"]["株洲"].push({
  code: "ZZA",
  name: "株洲德熙行汽车贸易有限公司"
});

_citys["四川"]["南充"].push({
  code: "NAA",
  name: "南充瑞和品信汽车销售服务有限公司"
});

_citys["湖北"]["襄阳"].push({
  code: "XYC",
  name: "襄阳建银瑞沃汽车销售服务有限公司"
});

_citys["广东"]["深圳"].push({
  code: "SZD",
  name: "深圳鼎沃汽车销售服务有限公司"
});

_citys["湖北"]["武汉"].push({
  code: "WHF",
  name: "武汉建银富瑞汽车销售服务有限公司"
});

_citys["重庆"]["重庆"].push({
  code: "CQD",
  name: "重庆万友都成汽车销售服务有限公司"
});

_citys["安徽"]["合肥"].push({
  code: "HFD",
  name: "合肥恒信德龙瑞沃汽车销售服务有限公司"
});

_citys["广西"]["桂林"].push({
  code: "GLA",
  name: "桂林弘沃汽车销售服务有限公司"
});

_citys["浙江"]["宁波"].push({
  code: "NBD",
  name: "宁波沃龙汽车服务有限公司"
});

_citys["河南"]["南阳"].push({
  code: "NYA",
  name: "南阳宛沃汽车销售服务有限公司"
});

_citys["陕西"]["咸阳"].push({
  code: "XYA",
  name: "咸阳新丰泰瑞嘉汽车销售服务有限公司"
});

_citys["福建"]["莆田"].push({
  code: "PTA",
  name: "莆田吉诺富豪汽车销售服务有限公司"
});

_citys["福建"]["福州"].push({
  code: "FZA",
  name: "福州鼎沃汽车销售服务有限公司"
});

_citys["广东"]["广州"].push({
  code: "GZD",
  name: "广东广物君沃汽车销售服务有限公司"
});

_citys["吉林"]["吉林"].push({
  code: "JLA",
  name: "吉林维信汽车销售有限公司"
});

_citys["浙江"]["金华"].push({
  code: "JHC",
  name: "金华中沃汽车销售服务有限公司"
});

_citys["陕西"]["宝鸡"].push({
  code: "BJZ",
  name: "宝鸡宝沃汽车销售服务有限公司"
});

_citys["陕西"]["延安"].push({
  code: "YAA",
  name: "延安广汇鑫汽车销售服务有限公司"
});

_citys["山东"]["济南"].push({
  code: "JNG",
  name: "山东京泰汽车贸易有限公司"
});

_citys["浙江"]["义乌"].push({
  code: "YWA",
  name: "义乌市金沃汽车销售有限公司"
});

_citys["四川"]["成都"].push({
  code: "CDE",
  name: "四川申蓉汇亚汽车贸易有限公司"
});

_citys["广东"]["深圳"].push({
  code: "SZC",
  name: "深圳市德顺行汽车销售服务有限公司"
});

_citys["河南"]["新乡"].push({
  code: "XXA",
  name: "新乡市东安沃达汽车销售服务有限公司"
});

_citys["重庆"]["重庆"].push({
  code: "CQE",
  name: "万友汽车投资有限公司重庆南坪分公司"
});

_citys["北京"]["北京"].push({
  code: "BJO",
  name: "北京正通鼎沃汽车销售服务有限公司"
});

_citys["浙江"]["温州"].push({
  code: "WZD",
  name: "温州荣沃汽车销售服务有限公司"
});

_citys["江苏"]["苏州"].push({
  code: "SUB",
  name: "通孚祥（苏州）汽车销售服务有限公司昆山分公司"
});

_citys["河南"]["郑州"].push({
  code: "HNF",
  name: "郑州中沃汽车销售服务有限公司"
});

_citys["河北"]["沧州"].push({
  code: "HBH",
  name: "沧州市德联汇源汽车贸易有限公司"
});

_citys["河北"]["石家庄"].push({
  code: "HBG",
  name: "河北瑞沃商贸有限公司"
});

_citys["四川"]["成都"].push({
  code: "CDF",
  name: "成都祥沃汽车销售服务有限公司"
});

_citys["江苏"]["南京"].push({
  code: "NJA",
  name: "南京世贸泰信汽车销售服务有限公司"
});

_citys["山西"]["临汾"].push({
  code: "LFA",
  name: "临汾海之沃汽车服务有限公司"
});

_citys["浙江"]["舟山"].push({
  code: "ZSB",
  name: "舟山永杰汽车销售服务有限公司"
});

_citys["山西"]["运城"].push({
  code: "YUA",
  name: "运城海之沃汽车服务有限公司"
});

_citys["河南"]["郑州"].push({
  code: "HNH",
  name: "郑州东沃汽车销售有限公司"
});

_citys["重庆"]["重庆"].push({
  code: "CQF",
  name: "重庆高新璟沃汽车有限公司"
});

_citys["陕西"]["西安"].push({
  code: "XAE",
  name: "陕西天一汇通汽车销售服务有限公司"
});

window.onload = function() {
  riot.mount("*");
  $(".show-pop").on("click", function() {
    i = $(this).index() + 1;
    $(".pop .content").html('<img src="img/pop-' + i + '.png" />');
    return $(".pop").show();
  });
  $(".pop").on("click", function() {
    return $(".pop").hide();
  });
  return $(".backTop").on("click", function() {
    return window.scrollTo(0, $(".bg-2").offset().top - 80);
  });
};

changePoint = function(i) {
  console.log(Math.abs(i));
  $(".points span").removeClass("on");
  return $(".points span").eq(Math.abs(i)).addClass("on");
};
